// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProcessMetricas.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ProcessMetricas_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ProcessMetricas_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ProcessMetricas_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ProcessMetricas_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ProcessMetricas_2eproto;
namespace ProcessMetricas {
class InstalledProgram;
struct InstalledProgramDefaultTypeInternal;
extern InstalledProgramDefaultTypeInternal _InstalledProgram_default_instance_;
class InstalledProgramList;
struct InstalledProgramListDefaultTypeInternal;
extern InstalledProgramListDefaultTypeInternal _InstalledProgramList_default_instance_;
class KernelDistro;
struct KernelDistroDefaultTypeInternal;
extern KernelDistroDefaultTypeInternal _KernelDistro_default_instance_;
class ProcessMetrics;
struct ProcessMetricsDefaultTypeInternal;
extern ProcessMetricsDefaultTypeInternal _ProcessMetrics_default_instance_;
class ProcessMetricsList;
struct ProcessMetricsListDefaultTypeInternal;
extern ProcessMetricsListDefaultTypeInternal _ProcessMetricsList_default_instance_;
}  // namespace ProcessMetricas
PROTOBUF_NAMESPACE_OPEN
template<> ::ProcessMetricas::InstalledProgram* Arena::CreateMaybeMessage<::ProcessMetricas::InstalledProgram>(Arena*);
template<> ::ProcessMetricas::InstalledProgramList* Arena::CreateMaybeMessage<::ProcessMetricas::InstalledProgramList>(Arena*);
template<> ::ProcessMetricas::KernelDistro* Arena::CreateMaybeMessage<::ProcessMetricas::KernelDistro>(Arena*);
template<> ::ProcessMetricas::ProcessMetrics* Arena::CreateMaybeMessage<::ProcessMetricas::ProcessMetrics>(Arena*);
template<> ::ProcessMetricas::ProcessMetricsList* Arena::CreateMaybeMessage<::ProcessMetricas::ProcessMetricsList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ProcessMetricas {

// ===================================================================

class ProcessMetrics final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProcessMetricas.ProcessMetrics) */ {
 public:
  inline ProcessMetrics() : ProcessMetrics(nullptr) {}
  ~ProcessMetrics() override;
  explicit PROTOBUF_CONSTEXPR ProcessMetrics(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProcessMetrics(const ProcessMetrics& from);
  ProcessMetrics(ProcessMetrics&& from) noexcept
    : ProcessMetrics() {
    *this = ::std::move(from);
  }

  inline ProcessMetrics& operator=(const ProcessMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProcessMetrics& operator=(ProcessMetrics&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProcessMetrics& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProcessMetrics* internal_default_instance() {
    return reinterpret_cast<const ProcessMetrics*>(
               &_ProcessMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ProcessMetrics& a, ProcessMetrics& b) {
    a.Swap(&b);
  }
  inline void Swap(ProcessMetrics* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProcessMetrics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProcessMetrics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProcessMetrics>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProcessMetrics& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProcessMetrics& from) {
    ProcessMetrics::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProcessMetrics* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProcessMetricas.ProcessMetrics";
  }
  protected:
  explicit ProcessMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kUserFieldNumber = 3,
    kTimestampFieldNumber = 4,
    kBoottimeFieldNumber = 15,
    kTimestartprocessFieldNumber = 16,
    kHostipFieldNumber = 17,
    kPidFieldNumber = 1,
    kNumThreadsFieldNumber = 7,
    kCpuPercentFieldNumber = 8,
    kNumChildProcessesFieldNumber = 9,
    kReadBytesKbFieldNumber = 11,
    kMemoryPercentFieldNumber = 10,
    kNumFdsFieldNumber = 13,
    kWriteBytesKbFieldNumber = 12,
    kNiceFieldNumber = 14,
    kIoniceValueFieldNumber = 20,
    kGidEffectiveFieldNumber = 21,
    kMemRssKbFieldNumber = 23,
    kMemSharedKbFieldNumber = 25,
    kMemVmsKbFieldNumber = 26,
    kMemTextKbFieldNumber = 27,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string user = 3;
  void clear_user();
  const std::string& user() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user();
  PROTOBUF_NODISCARD std::string* release_user();
  void set_allocated_user(std::string* user);
  private:
  const std::string& _internal_user() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user(const std::string& value);
  std::string* _internal_mutable_user();
  public:

  // string timestamp = 4;
  void clear_timestamp();
  const std::string& timestamp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timestamp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* timestamp);
  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const std::string& value);
  std::string* _internal_mutable_timestamp();
  public:

  // string boottime = 15;
  void clear_boottime();
  const std::string& boottime() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_boottime(ArgT0&& arg0, ArgT... args);
  std::string* mutable_boottime();
  PROTOBUF_NODISCARD std::string* release_boottime();
  void set_allocated_boottime(std::string* boottime);
  private:
  const std::string& _internal_boottime() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_boottime(const std::string& value);
  std::string* _internal_mutable_boottime();
  public:

  // string timestartprocess = 16;
  void clear_timestartprocess();
  const std::string& timestartprocess() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timestartprocess(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timestartprocess();
  PROTOBUF_NODISCARD std::string* release_timestartprocess();
  void set_allocated_timestartprocess(std::string* timestartprocess);
  private:
  const std::string& _internal_timestartprocess() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestartprocess(const std::string& value);
  std::string* _internal_mutable_timestartprocess();
  public:

  // string hostip = 17;
  void clear_hostip();
  const std::string& hostip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_hostip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_hostip();
  PROTOBUF_NODISCARD std::string* release_hostip();
  void set_allocated_hostip(std::string* hostip);
  private:
  const std::string& _internal_hostip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hostip(const std::string& value);
  std::string* _internal_mutable_hostip();
  public:

  // int32 pid = 1;
  void clear_pid();
  int32_t pid() const;
  void set_pid(int32_t value);
  private:
  int32_t _internal_pid() const;
  void _internal_set_pid(int32_t value);
  public:

  // int32 num_threads = 7;
  void clear_num_threads();
  int32_t num_threads() const;
  void set_num_threads(int32_t value);
  private:
  int32_t _internal_num_threads() const;
  void _internal_set_num_threads(int32_t value);
  public:

  // optional float cpu_percent = 8;
  bool has_cpu_percent() const;
  private:
  bool _internal_has_cpu_percent() const;
  public:
  void clear_cpu_percent();
  float cpu_percent() const;
  void set_cpu_percent(float value);
  private:
  float _internal_cpu_percent() const;
  void _internal_set_cpu_percent(float value);
  public:

  // optional int32 num_child_processes = 9;
  bool has_num_child_processes() const;
  private:
  bool _internal_has_num_child_processes() const;
  public:
  void clear_num_child_processes();
  int32_t num_child_processes() const;
  void set_num_child_processes(int32_t value);
  private:
  int32_t _internal_num_child_processes() const;
  void _internal_set_num_child_processes(int32_t value);
  public:

  // optional uint64 read_bytes_kb = 11;
  bool has_read_bytes_kb() const;
  private:
  bool _internal_has_read_bytes_kb() const;
  public:
  void clear_read_bytes_kb();
  uint64_t read_bytes_kb() const;
  void set_read_bytes_kb(uint64_t value);
  private:
  uint64_t _internal_read_bytes_kb() const;
  void _internal_set_read_bytes_kb(uint64_t value);
  public:

  // optional float memory_percent = 10;
  bool has_memory_percent() const;
  private:
  bool _internal_has_memory_percent() const;
  public:
  void clear_memory_percent();
  float memory_percent() const;
  void set_memory_percent(float value);
  private:
  float _internal_memory_percent() const;
  void _internal_set_memory_percent(float value);
  public:

  // optional int32 num_fds = 13;
  bool has_num_fds() const;
  private:
  bool _internal_has_num_fds() const;
  public:
  void clear_num_fds();
  int32_t num_fds() const;
  void set_num_fds(int32_t value);
  private:
  int32_t _internal_num_fds() const;
  void _internal_set_num_fds(int32_t value);
  public:

  // optional uint64 write_bytes_kb = 12;
  bool has_write_bytes_kb() const;
  private:
  bool _internal_has_write_bytes_kb() const;
  public:
  void clear_write_bytes_kb();
  uint64_t write_bytes_kb() const;
  void set_write_bytes_kb(uint64_t value);
  private:
  uint64_t _internal_write_bytes_kb() const;
  void _internal_set_write_bytes_kb(uint64_t value);
  public:

  // int32 nice = 14;
  void clear_nice();
  int32_t nice() const;
  void set_nice(int32_t value);
  private:
  int32_t _internal_nice() const;
  void _internal_set_nice(int32_t value);
  public:

  // int32 ionice_value = 20;
  void clear_ionice_value();
  int32_t ionice_value() const;
  void set_ionice_value(int32_t value);
  private:
  int32_t _internal_ionice_value() const;
  void _internal_set_ionice_value(int32_t value);
  public:

  // int32 gid_effective = 21;
  void clear_gid_effective();
  int32_t gid_effective() const;
  void set_gid_effective(int32_t value);
  private:
  int32_t _internal_gid_effective() const;
  void _internal_set_gid_effective(int32_t value);
  public:

  // int32 mem_rss_kb = 23;
  void clear_mem_rss_kb();
  int32_t mem_rss_kb() const;
  void set_mem_rss_kb(int32_t value);
  private:
  int32_t _internal_mem_rss_kb() const;
  void _internal_set_mem_rss_kb(int32_t value);
  public:

  // int32 mem_shared_kb = 25;
  void clear_mem_shared_kb();
  int32_t mem_shared_kb() const;
  void set_mem_shared_kb(int32_t value);
  private:
  int32_t _internal_mem_shared_kb() const;
  void _internal_set_mem_shared_kb(int32_t value);
  public:

  // int32 mem_vms_kb = 26;
  void clear_mem_vms_kb();
  int32_t mem_vms_kb() const;
  void set_mem_vms_kb(int32_t value);
  private:
  int32_t _internal_mem_vms_kb() const;
  void _internal_set_mem_vms_kb(int32_t value);
  public:

  // int32 mem_text_kb = 27;
  void clear_mem_text_kb();
  int32_t mem_text_kb() const;
  void set_mem_text_kb(int32_t value);
  private:
  int32_t _internal_mem_text_kb() const;
  void _internal_set_mem_text_kb(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ProcessMetricas.ProcessMetrics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestamp_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr boottime_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestartprocess_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hostip_;
    int32_t pid_;
    int32_t num_threads_;
    float cpu_percent_;
    int32_t num_child_processes_;
    uint64_t read_bytes_kb_;
    float memory_percent_;
    int32_t num_fds_;
    uint64_t write_bytes_kb_;
    int32_t nice_;
    int32_t ionice_value_;
    int32_t gid_effective_;
    int32_t mem_rss_kb_;
    int32_t mem_shared_kb_;
    int32_t mem_vms_kb_;
    int32_t mem_text_kb_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProcessMetricas_2eproto;
};
// -------------------------------------------------------------------

class ProcessMetricsList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProcessMetricas.ProcessMetricsList) */ {
 public:
  inline ProcessMetricsList() : ProcessMetricsList(nullptr) {}
  ~ProcessMetricsList() override;
  explicit PROTOBUF_CONSTEXPR ProcessMetricsList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProcessMetricsList(const ProcessMetricsList& from);
  ProcessMetricsList(ProcessMetricsList&& from) noexcept
    : ProcessMetricsList() {
    *this = ::std::move(from);
  }

  inline ProcessMetricsList& operator=(const ProcessMetricsList& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProcessMetricsList& operator=(ProcessMetricsList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProcessMetricsList& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProcessMetricsList* internal_default_instance() {
    return reinterpret_cast<const ProcessMetricsList*>(
               &_ProcessMetricsList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ProcessMetricsList& a, ProcessMetricsList& b) {
    a.Swap(&b);
  }
  inline void Swap(ProcessMetricsList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProcessMetricsList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProcessMetricsList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProcessMetricsList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProcessMetricsList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProcessMetricsList& from) {
    ProcessMetricsList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProcessMetricsList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProcessMetricas.ProcessMetricsList";
  }
  protected:
  explicit ProcessMetricsList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProcessesFieldNumber = 1,
  };
  // repeated .ProcessMetricas.ProcessMetrics processes = 1;
  int processes_size() const;
  private:
  int _internal_processes_size() const;
  public:
  void clear_processes();
  ::ProcessMetricas::ProcessMetrics* mutable_processes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::ProcessMetrics >*
      mutable_processes();
  private:
  const ::ProcessMetricas::ProcessMetrics& _internal_processes(int index) const;
  ::ProcessMetricas::ProcessMetrics* _internal_add_processes();
  public:
  const ::ProcessMetricas::ProcessMetrics& processes(int index) const;
  ::ProcessMetricas::ProcessMetrics* add_processes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::ProcessMetrics >&
      processes() const;

  // @@protoc_insertion_point(class_scope:ProcessMetricas.ProcessMetricsList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::ProcessMetrics > processes_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProcessMetricas_2eproto;
};
// -------------------------------------------------------------------

class KernelDistro final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProcessMetricas.KernelDistro) */ {
 public:
  inline KernelDistro() : KernelDistro(nullptr) {}
  ~KernelDistro() override;
  explicit PROTOBUF_CONSTEXPR KernelDistro(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  KernelDistro(const KernelDistro& from);
  KernelDistro(KernelDistro&& from) noexcept
    : KernelDistro() {
    *this = ::std::move(from);
  }

  inline KernelDistro& operator=(const KernelDistro& from) {
    CopyFrom(from);
    return *this;
  }
  inline KernelDistro& operator=(KernelDistro&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const KernelDistro& default_instance() {
    return *internal_default_instance();
  }
  static inline const KernelDistro* internal_default_instance() {
    return reinterpret_cast<const KernelDistro*>(
               &_KernelDistro_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(KernelDistro& a, KernelDistro& b) {
    a.Swap(&b);
  }
  inline void Swap(KernelDistro* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(KernelDistro* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  KernelDistro* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<KernelDistro>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const KernelDistro& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const KernelDistro& from) {
    KernelDistro::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(KernelDistro* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProcessMetricas.KernelDistro";
  }
  protected:
  explicit KernelDistro(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kKernelVersionFieldNumber = 1,
    kDistroNameFieldNumber = 2,
    kTimestampFieldNumber = 3,
    kHostipFieldNumber = 17,
  };
  // string kernel_version = 1;
  void clear_kernel_version();
  const std::string& kernel_version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_kernel_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_kernel_version();
  PROTOBUF_NODISCARD std::string* release_kernel_version();
  void set_allocated_kernel_version(std::string* kernel_version);
  private:
  const std::string& _internal_kernel_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_kernel_version(const std::string& value);
  std::string* _internal_mutable_kernel_version();
  public:

  // string distro_name = 2;
  void clear_distro_name();
  const std::string& distro_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_distro_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_distro_name();
  PROTOBUF_NODISCARD std::string* release_distro_name();
  void set_allocated_distro_name(std::string* distro_name);
  private:
  const std::string& _internal_distro_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_distro_name(const std::string& value);
  std::string* _internal_mutable_distro_name();
  public:

  // string timestamp = 3;
  void clear_timestamp();
  const std::string& timestamp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timestamp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* timestamp);
  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const std::string& value);
  std::string* _internal_mutable_timestamp();
  public:

  // string hostip = 17;
  void clear_hostip();
  const std::string& hostip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_hostip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_hostip();
  PROTOBUF_NODISCARD std::string* release_hostip();
  void set_allocated_hostip(std::string* hostip);
  private:
  const std::string& _internal_hostip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hostip(const std::string& value);
  std::string* _internal_mutable_hostip();
  public:

  // @@protoc_insertion_point(class_scope:ProcessMetricas.KernelDistro)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr kernel_version_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr distro_name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestamp_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hostip_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProcessMetricas_2eproto;
};
// -------------------------------------------------------------------

class InstalledProgram final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProcessMetricas.InstalledProgram) */ {
 public:
  inline InstalledProgram() : InstalledProgram(nullptr) {}
  ~InstalledProgram() override;
  explicit PROTOBUF_CONSTEXPR InstalledProgram(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InstalledProgram(const InstalledProgram& from);
  InstalledProgram(InstalledProgram&& from) noexcept
    : InstalledProgram() {
    *this = ::std::move(from);
  }

  inline InstalledProgram& operator=(const InstalledProgram& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstalledProgram& operator=(InstalledProgram&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InstalledProgram& default_instance() {
    return *internal_default_instance();
  }
  static inline const InstalledProgram* internal_default_instance() {
    return reinterpret_cast<const InstalledProgram*>(
               &_InstalledProgram_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(InstalledProgram& a, InstalledProgram& b) {
    a.Swap(&b);
  }
  inline void Swap(InstalledProgram* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstalledProgram* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InstalledProgram* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InstalledProgram>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InstalledProgram& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InstalledProgram& from) {
    InstalledProgram::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstalledProgram* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProcessMetricas.InstalledProgram";
  }
  protected:
  explicit InstalledProgram(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 1,
    kVersionFieldNumber = 2,
  };
  // string name = 1;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string version = 2;
  void clear_version();
  const std::string& version() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_version(ArgT0&& arg0, ArgT... args);
  std::string* mutable_version();
  PROTOBUF_NODISCARD std::string* release_version();
  void set_allocated_version(std::string* version);
  private:
  const std::string& _internal_version() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_version(const std::string& value);
  std::string* _internal_mutable_version();
  public:

  // @@protoc_insertion_point(class_scope:ProcessMetricas.InstalledProgram)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr version_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProcessMetricas_2eproto;
};
// -------------------------------------------------------------------

class InstalledProgramList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProcessMetricas.InstalledProgramList) */ {
 public:
  inline InstalledProgramList() : InstalledProgramList(nullptr) {}
  ~InstalledProgramList() override;
  explicit PROTOBUF_CONSTEXPR InstalledProgramList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  InstalledProgramList(const InstalledProgramList& from);
  InstalledProgramList(InstalledProgramList&& from) noexcept
    : InstalledProgramList() {
    *this = ::std::move(from);
  }

  inline InstalledProgramList& operator=(const InstalledProgramList& from) {
    CopyFrom(from);
    return *this;
  }
  inline InstalledProgramList& operator=(InstalledProgramList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const InstalledProgramList& default_instance() {
    return *internal_default_instance();
  }
  static inline const InstalledProgramList* internal_default_instance() {
    return reinterpret_cast<const InstalledProgramList*>(
               &_InstalledProgramList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(InstalledProgramList& a, InstalledProgramList& b) {
    a.Swap(&b);
  }
  inline void Swap(InstalledProgramList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(InstalledProgramList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  InstalledProgramList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<InstalledProgramList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const InstalledProgramList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const InstalledProgramList& from) {
    InstalledProgramList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(InstalledProgramList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProcessMetricas.InstalledProgramList";
  }
  protected:
  explicit InstalledProgramList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProgramsFieldNumber = 1,
    kHostipFieldNumber = 2,
    kTimestampFieldNumber = 3,
  };
  // repeated .ProcessMetricas.InstalledProgram programs = 1;
  int programs_size() const;
  private:
  int _internal_programs_size() const;
  public:
  void clear_programs();
  ::ProcessMetricas::InstalledProgram* mutable_programs(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::InstalledProgram >*
      mutable_programs();
  private:
  const ::ProcessMetricas::InstalledProgram& _internal_programs(int index) const;
  ::ProcessMetricas::InstalledProgram* _internal_add_programs();
  public:
  const ::ProcessMetricas::InstalledProgram& programs(int index) const;
  ::ProcessMetricas::InstalledProgram* add_programs();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::InstalledProgram >&
      programs() const;

  // string hostip = 2;
  void clear_hostip();
  const std::string& hostip() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_hostip(ArgT0&& arg0, ArgT... args);
  std::string* mutable_hostip();
  PROTOBUF_NODISCARD std::string* release_hostip();
  void set_allocated_hostip(std::string* hostip);
  private:
  const std::string& _internal_hostip() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_hostip(const std::string& value);
  std::string* _internal_mutable_hostip();
  public:

  // string timestamp = 3;
  void clear_timestamp();
  const std::string& timestamp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timestamp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* timestamp);
  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const std::string& value);
  std::string* _internal_mutable_timestamp();
  public:

  // @@protoc_insertion_point(class_scope:ProcessMetricas.InstalledProgramList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::InstalledProgram > programs_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr hostip_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestamp_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProcessMetricas_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProcessMetrics

// int32 pid = 1;
inline void ProcessMetrics::clear_pid() {
  _impl_.pid_ = 0;
}
inline int32_t ProcessMetrics::_internal_pid() const {
  return _impl_.pid_;
}
inline int32_t ProcessMetrics::pid() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.pid)
  return _internal_pid();
}
inline void ProcessMetrics::_internal_set_pid(int32_t value) {
  
  _impl_.pid_ = value;
}
inline void ProcessMetrics::set_pid(int32_t value) {
  _internal_set_pid(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.pid)
}

// string name = 2;
inline void ProcessMetrics::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& ProcessMetrics::name() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProcessMetrics::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.name)
}
inline std::string* ProcessMetrics::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.ProcessMetrics.name)
  return _s;
}
inline const std::string& ProcessMetrics::_internal_name() const {
  return _impl_.name_.Get();
}
inline void ProcessMetrics::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* ProcessMetrics::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* ProcessMetrics::release_name() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.ProcessMetrics.name)
  return _impl_.name_.Release();
}
inline void ProcessMetrics::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.ProcessMetrics.name)
}

// string user = 3;
inline void ProcessMetrics::clear_user() {
  _impl_.user_.ClearToEmpty();
}
inline const std::string& ProcessMetrics::user() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.user)
  return _internal_user();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProcessMetrics::set_user(ArgT0&& arg0, ArgT... args) {
 
 _impl_.user_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.user)
}
inline std::string* ProcessMetrics::mutable_user() {
  std::string* _s = _internal_mutable_user();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.ProcessMetrics.user)
  return _s;
}
inline const std::string& ProcessMetrics::_internal_user() const {
  return _impl_.user_.Get();
}
inline void ProcessMetrics::_internal_set_user(const std::string& value) {
  
  _impl_.user_.Set(value, GetArenaForAllocation());
}
inline std::string* ProcessMetrics::_internal_mutable_user() {
  
  return _impl_.user_.Mutable(GetArenaForAllocation());
}
inline std::string* ProcessMetrics::release_user() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.ProcessMetrics.user)
  return _impl_.user_.Release();
}
inline void ProcessMetrics::set_allocated_user(std::string* user) {
  if (user != nullptr) {
    
  } else {
    
  }
  _impl_.user_.SetAllocated(user, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_.IsDefault()) {
    _impl_.user_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.ProcessMetrics.user)
}

// int32 num_threads = 7;
inline void ProcessMetrics::clear_num_threads() {
  _impl_.num_threads_ = 0;
}
inline int32_t ProcessMetrics::_internal_num_threads() const {
  return _impl_.num_threads_;
}
inline int32_t ProcessMetrics::num_threads() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.num_threads)
  return _internal_num_threads();
}
inline void ProcessMetrics::_internal_set_num_threads(int32_t value) {
  
  _impl_.num_threads_ = value;
}
inline void ProcessMetrics::set_num_threads(int32_t value) {
  _internal_set_num_threads(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.num_threads)
}

// optional int32 num_child_processes = 9;
inline bool ProcessMetrics::_internal_has_num_child_processes() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool ProcessMetrics::has_num_child_processes() const {
  return _internal_has_num_child_processes();
}
inline void ProcessMetrics::clear_num_child_processes() {
  _impl_.num_child_processes_ = 0;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline int32_t ProcessMetrics::_internal_num_child_processes() const {
  return _impl_.num_child_processes_;
}
inline int32_t ProcessMetrics::num_child_processes() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.num_child_processes)
  return _internal_num_child_processes();
}
inline void ProcessMetrics::_internal_set_num_child_processes(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.num_child_processes_ = value;
}
inline void ProcessMetrics::set_num_child_processes(int32_t value) {
  _internal_set_num_child_processes(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.num_child_processes)
}

// optional float cpu_percent = 8;
inline bool ProcessMetrics::_internal_has_cpu_percent() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool ProcessMetrics::has_cpu_percent() const {
  return _internal_has_cpu_percent();
}
inline void ProcessMetrics::clear_cpu_percent() {
  _impl_.cpu_percent_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline float ProcessMetrics::_internal_cpu_percent() const {
  return _impl_.cpu_percent_;
}
inline float ProcessMetrics::cpu_percent() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.cpu_percent)
  return _internal_cpu_percent();
}
inline void ProcessMetrics::_internal_set_cpu_percent(float value) {
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.cpu_percent_ = value;
}
inline void ProcessMetrics::set_cpu_percent(float value) {
  _internal_set_cpu_percent(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.cpu_percent)
}

// optional float memory_percent = 10;
inline bool ProcessMetrics::_internal_has_memory_percent() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool ProcessMetrics::has_memory_percent() const {
  return _internal_has_memory_percent();
}
inline void ProcessMetrics::clear_memory_percent() {
  _impl_.memory_percent_ = 0;
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline float ProcessMetrics::_internal_memory_percent() const {
  return _impl_.memory_percent_;
}
inline float ProcessMetrics::memory_percent() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.memory_percent)
  return _internal_memory_percent();
}
inline void ProcessMetrics::_internal_set_memory_percent(float value) {
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.memory_percent_ = value;
}
inline void ProcessMetrics::set_memory_percent(float value) {
  _internal_set_memory_percent(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.memory_percent)
}

// int32 mem_rss_kb = 23;
inline void ProcessMetrics::clear_mem_rss_kb() {
  _impl_.mem_rss_kb_ = 0;
}
inline int32_t ProcessMetrics::_internal_mem_rss_kb() const {
  return _impl_.mem_rss_kb_;
}
inline int32_t ProcessMetrics::mem_rss_kb() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.mem_rss_kb)
  return _internal_mem_rss_kb();
}
inline void ProcessMetrics::_internal_set_mem_rss_kb(int32_t value) {
  
  _impl_.mem_rss_kb_ = value;
}
inline void ProcessMetrics::set_mem_rss_kb(int32_t value) {
  _internal_set_mem_rss_kb(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.mem_rss_kb)
}

// int32 mem_shared_kb = 25;
inline void ProcessMetrics::clear_mem_shared_kb() {
  _impl_.mem_shared_kb_ = 0;
}
inline int32_t ProcessMetrics::_internal_mem_shared_kb() const {
  return _impl_.mem_shared_kb_;
}
inline int32_t ProcessMetrics::mem_shared_kb() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.mem_shared_kb)
  return _internal_mem_shared_kb();
}
inline void ProcessMetrics::_internal_set_mem_shared_kb(int32_t value) {
  
  _impl_.mem_shared_kb_ = value;
}
inline void ProcessMetrics::set_mem_shared_kb(int32_t value) {
  _internal_set_mem_shared_kb(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.mem_shared_kb)
}

// int32 mem_vms_kb = 26;
inline void ProcessMetrics::clear_mem_vms_kb() {
  _impl_.mem_vms_kb_ = 0;
}
inline int32_t ProcessMetrics::_internal_mem_vms_kb() const {
  return _impl_.mem_vms_kb_;
}
inline int32_t ProcessMetrics::mem_vms_kb() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.mem_vms_kb)
  return _internal_mem_vms_kb();
}
inline void ProcessMetrics::_internal_set_mem_vms_kb(int32_t value) {
  
  _impl_.mem_vms_kb_ = value;
}
inline void ProcessMetrics::set_mem_vms_kb(int32_t value) {
  _internal_set_mem_vms_kb(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.mem_vms_kb)
}

// int32 mem_text_kb = 27;
inline void ProcessMetrics::clear_mem_text_kb() {
  _impl_.mem_text_kb_ = 0;
}
inline int32_t ProcessMetrics::_internal_mem_text_kb() const {
  return _impl_.mem_text_kb_;
}
inline int32_t ProcessMetrics::mem_text_kb() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.mem_text_kb)
  return _internal_mem_text_kb();
}
inline void ProcessMetrics::_internal_set_mem_text_kb(int32_t value) {
  
  _impl_.mem_text_kb_ = value;
}
inline void ProcessMetrics::set_mem_text_kb(int32_t value) {
  _internal_set_mem_text_kb(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.mem_text_kb)
}

// optional uint64 read_bytes_kb = 11;
inline bool ProcessMetrics::_internal_has_read_bytes_kb() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool ProcessMetrics::has_read_bytes_kb() const {
  return _internal_has_read_bytes_kb();
}
inline void ProcessMetrics::clear_read_bytes_kb() {
  _impl_.read_bytes_kb_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline uint64_t ProcessMetrics::_internal_read_bytes_kb() const {
  return _impl_.read_bytes_kb_;
}
inline uint64_t ProcessMetrics::read_bytes_kb() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.read_bytes_kb)
  return _internal_read_bytes_kb();
}
inline void ProcessMetrics::_internal_set_read_bytes_kb(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.read_bytes_kb_ = value;
}
inline void ProcessMetrics::set_read_bytes_kb(uint64_t value) {
  _internal_set_read_bytes_kb(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.read_bytes_kb)
}

// optional uint64 write_bytes_kb = 12;
inline bool ProcessMetrics::_internal_has_write_bytes_kb() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool ProcessMetrics::has_write_bytes_kb() const {
  return _internal_has_write_bytes_kb();
}
inline void ProcessMetrics::clear_write_bytes_kb() {
  _impl_.write_bytes_kb_ = uint64_t{0u};
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline uint64_t ProcessMetrics::_internal_write_bytes_kb() const {
  return _impl_.write_bytes_kb_;
}
inline uint64_t ProcessMetrics::write_bytes_kb() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.write_bytes_kb)
  return _internal_write_bytes_kb();
}
inline void ProcessMetrics::_internal_set_write_bytes_kb(uint64_t value) {
  _impl_._has_bits_[0] |= 0x00000020u;
  _impl_.write_bytes_kb_ = value;
}
inline void ProcessMetrics::set_write_bytes_kb(uint64_t value) {
  _internal_set_write_bytes_kb(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.write_bytes_kb)
}

// optional int32 num_fds = 13;
inline bool ProcessMetrics::_internal_has_num_fds() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool ProcessMetrics::has_num_fds() const {
  return _internal_has_num_fds();
}
inline void ProcessMetrics::clear_num_fds() {
  _impl_.num_fds_ = 0;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline int32_t ProcessMetrics::_internal_num_fds() const {
  return _impl_.num_fds_;
}
inline int32_t ProcessMetrics::num_fds() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.num_fds)
  return _internal_num_fds();
}
inline void ProcessMetrics::_internal_set_num_fds(int32_t value) {
  _impl_._has_bits_[0] |= 0x00000010u;
  _impl_.num_fds_ = value;
}
inline void ProcessMetrics::set_num_fds(int32_t value) {
  _internal_set_num_fds(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.num_fds)
}

// int32 nice = 14;
inline void ProcessMetrics::clear_nice() {
  _impl_.nice_ = 0;
}
inline int32_t ProcessMetrics::_internal_nice() const {
  return _impl_.nice_;
}
inline int32_t ProcessMetrics::nice() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.nice)
  return _internal_nice();
}
inline void ProcessMetrics::_internal_set_nice(int32_t value) {
  
  _impl_.nice_ = value;
}
inline void ProcessMetrics::set_nice(int32_t value) {
  _internal_set_nice(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.nice)
}

// int32 ionice_value = 20;
inline void ProcessMetrics::clear_ionice_value() {
  _impl_.ionice_value_ = 0;
}
inline int32_t ProcessMetrics::_internal_ionice_value() const {
  return _impl_.ionice_value_;
}
inline int32_t ProcessMetrics::ionice_value() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.ionice_value)
  return _internal_ionice_value();
}
inline void ProcessMetrics::_internal_set_ionice_value(int32_t value) {
  
  _impl_.ionice_value_ = value;
}
inline void ProcessMetrics::set_ionice_value(int32_t value) {
  _internal_set_ionice_value(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.ionice_value)
}

// string timestamp = 4;
inline void ProcessMetrics::clear_timestamp() {
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& ProcessMetrics::timestamp() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.timestamp)
  return _internal_timestamp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProcessMetrics::set_timestamp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timestamp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.timestamp)
}
inline std::string* ProcessMetrics::mutable_timestamp() {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.ProcessMetrics.timestamp)
  return _s;
}
inline const std::string& ProcessMetrics::_internal_timestamp() const {
  return _impl_.timestamp_.Get();
}
inline void ProcessMetrics::_internal_set_timestamp(const std::string& value) {
  
  _impl_.timestamp_.Set(value, GetArenaForAllocation());
}
inline std::string* ProcessMetrics::_internal_mutable_timestamp() {
  
  return _impl_.timestamp_.Mutable(GetArenaForAllocation());
}
inline std::string* ProcessMetrics::release_timestamp() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.ProcessMetrics.timestamp)
  return _impl_.timestamp_.Release();
}
inline void ProcessMetrics::set_allocated_timestamp(std::string* timestamp) {
  if (timestamp != nullptr) {
    
  } else {
    
  }
  _impl_.timestamp_.SetAllocated(timestamp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.ProcessMetrics.timestamp)
}

// string boottime = 15;
inline void ProcessMetrics::clear_boottime() {
  _impl_.boottime_.ClearToEmpty();
}
inline const std::string& ProcessMetrics::boottime() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.boottime)
  return _internal_boottime();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProcessMetrics::set_boottime(ArgT0&& arg0, ArgT... args) {
 
 _impl_.boottime_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.boottime)
}
inline std::string* ProcessMetrics::mutable_boottime() {
  std::string* _s = _internal_mutable_boottime();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.ProcessMetrics.boottime)
  return _s;
}
inline const std::string& ProcessMetrics::_internal_boottime() const {
  return _impl_.boottime_.Get();
}
inline void ProcessMetrics::_internal_set_boottime(const std::string& value) {
  
  _impl_.boottime_.Set(value, GetArenaForAllocation());
}
inline std::string* ProcessMetrics::_internal_mutable_boottime() {
  
  return _impl_.boottime_.Mutable(GetArenaForAllocation());
}
inline std::string* ProcessMetrics::release_boottime() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.ProcessMetrics.boottime)
  return _impl_.boottime_.Release();
}
inline void ProcessMetrics::set_allocated_boottime(std::string* boottime) {
  if (boottime != nullptr) {
    
  } else {
    
  }
  _impl_.boottime_.SetAllocated(boottime, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.boottime_.IsDefault()) {
    _impl_.boottime_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.ProcessMetrics.boottime)
}

// string timestartprocess = 16;
inline void ProcessMetrics::clear_timestartprocess() {
  _impl_.timestartprocess_.ClearToEmpty();
}
inline const std::string& ProcessMetrics::timestartprocess() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.timestartprocess)
  return _internal_timestartprocess();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProcessMetrics::set_timestartprocess(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timestartprocess_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.timestartprocess)
}
inline std::string* ProcessMetrics::mutable_timestartprocess() {
  std::string* _s = _internal_mutable_timestartprocess();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.ProcessMetrics.timestartprocess)
  return _s;
}
inline const std::string& ProcessMetrics::_internal_timestartprocess() const {
  return _impl_.timestartprocess_.Get();
}
inline void ProcessMetrics::_internal_set_timestartprocess(const std::string& value) {
  
  _impl_.timestartprocess_.Set(value, GetArenaForAllocation());
}
inline std::string* ProcessMetrics::_internal_mutable_timestartprocess() {
  
  return _impl_.timestartprocess_.Mutable(GetArenaForAllocation());
}
inline std::string* ProcessMetrics::release_timestartprocess() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.ProcessMetrics.timestartprocess)
  return _impl_.timestartprocess_.Release();
}
inline void ProcessMetrics::set_allocated_timestartprocess(std::string* timestartprocess) {
  if (timestartprocess != nullptr) {
    
  } else {
    
  }
  _impl_.timestartprocess_.SetAllocated(timestartprocess, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timestartprocess_.IsDefault()) {
    _impl_.timestartprocess_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.ProcessMetrics.timestartprocess)
}

// string hostip = 17;
inline void ProcessMetrics::clear_hostip() {
  _impl_.hostip_.ClearToEmpty();
}
inline const std::string& ProcessMetrics::hostip() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.hostip)
  return _internal_hostip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProcessMetrics::set_hostip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.hostip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.hostip)
}
inline std::string* ProcessMetrics::mutable_hostip() {
  std::string* _s = _internal_mutable_hostip();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.ProcessMetrics.hostip)
  return _s;
}
inline const std::string& ProcessMetrics::_internal_hostip() const {
  return _impl_.hostip_.Get();
}
inline void ProcessMetrics::_internal_set_hostip(const std::string& value) {
  
  _impl_.hostip_.Set(value, GetArenaForAllocation());
}
inline std::string* ProcessMetrics::_internal_mutable_hostip() {
  
  return _impl_.hostip_.Mutable(GetArenaForAllocation());
}
inline std::string* ProcessMetrics::release_hostip() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.ProcessMetrics.hostip)
  return _impl_.hostip_.Release();
}
inline void ProcessMetrics::set_allocated_hostip(std::string* hostip) {
  if (hostip != nullptr) {
    
  } else {
    
  }
  _impl_.hostip_.SetAllocated(hostip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.hostip_.IsDefault()) {
    _impl_.hostip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.ProcessMetrics.hostip)
}

// int32 gid_effective = 21;
inline void ProcessMetrics::clear_gid_effective() {
  _impl_.gid_effective_ = 0;
}
inline int32_t ProcessMetrics::_internal_gid_effective() const {
  return _impl_.gid_effective_;
}
inline int32_t ProcessMetrics::gid_effective() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.gid_effective)
  return _internal_gid_effective();
}
inline void ProcessMetrics::_internal_set_gid_effective(int32_t value) {
  
  _impl_.gid_effective_ = value;
}
inline void ProcessMetrics::set_gid_effective(int32_t value) {
  _internal_set_gid_effective(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.gid_effective)
}

// -------------------------------------------------------------------

// ProcessMetricsList

// repeated .ProcessMetricas.ProcessMetrics processes = 1;
inline int ProcessMetricsList::_internal_processes_size() const {
  return _impl_.processes_.size();
}
inline int ProcessMetricsList::processes_size() const {
  return _internal_processes_size();
}
inline void ProcessMetricsList::clear_processes() {
  _impl_.processes_.Clear();
}
inline ::ProcessMetricas::ProcessMetrics* ProcessMetricsList::mutable_processes(int index) {
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.ProcessMetricsList.processes)
  return _impl_.processes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::ProcessMetrics >*
ProcessMetricsList::mutable_processes() {
  // @@protoc_insertion_point(field_mutable_list:ProcessMetricas.ProcessMetricsList.processes)
  return &_impl_.processes_;
}
inline const ::ProcessMetricas::ProcessMetrics& ProcessMetricsList::_internal_processes(int index) const {
  return _impl_.processes_.Get(index);
}
inline const ::ProcessMetricas::ProcessMetrics& ProcessMetricsList::processes(int index) const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetricsList.processes)
  return _internal_processes(index);
}
inline ::ProcessMetricas::ProcessMetrics* ProcessMetricsList::_internal_add_processes() {
  return _impl_.processes_.Add();
}
inline ::ProcessMetricas::ProcessMetrics* ProcessMetricsList::add_processes() {
  ::ProcessMetricas::ProcessMetrics* _add = _internal_add_processes();
  // @@protoc_insertion_point(field_add:ProcessMetricas.ProcessMetricsList.processes)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::ProcessMetrics >&
ProcessMetricsList::processes() const {
  // @@protoc_insertion_point(field_list:ProcessMetricas.ProcessMetricsList.processes)
  return _impl_.processes_;
}

// -------------------------------------------------------------------

// KernelDistro

// string timestamp = 3;
inline void KernelDistro::clear_timestamp() {
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& KernelDistro::timestamp() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.KernelDistro.timestamp)
  return _internal_timestamp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KernelDistro::set_timestamp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timestamp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.KernelDistro.timestamp)
}
inline std::string* KernelDistro::mutable_timestamp() {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.KernelDistro.timestamp)
  return _s;
}
inline const std::string& KernelDistro::_internal_timestamp() const {
  return _impl_.timestamp_.Get();
}
inline void KernelDistro::_internal_set_timestamp(const std::string& value) {
  
  _impl_.timestamp_.Set(value, GetArenaForAllocation());
}
inline std::string* KernelDistro::_internal_mutable_timestamp() {
  
  return _impl_.timestamp_.Mutable(GetArenaForAllocation());
}
inline std::string* KernelDistro::release_timestamp() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.KernelDistro.timestamp)
  return _impl_.timestamp_.Release();
}
inline void KernelDistro::set_allocated_timestamp(std::string* timestamp) {
  if (timestamp != nullptr) {
    
  } else {
    
  }
  _impl_.timestamp_.SetAllocated(timestamp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.KernelDistro.timestamp)
}

// string kernel_version = 1;
inline void KernelDistro::clear_kernel_version() {
  _impl_.kernel_version_.ClearToEmpty();
}
inline const std::string& KernelDistro::kernel_version() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.KernelDistro.kernel_version)
  return _internal_kernel_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KernelDistro::set_kernel_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.kernel_version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.KernelDistro.kernel_version)
}
inline std::string* KernelDistro::mutable_kernel_version() {
  std::string* _s = _internal_mutable_kernel_version();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.KernelDistro.kernel_version)
  return _s;
}
inline const std::string& KernelDistro::_internal_kernel_version() const {
  return _impl_.kernel_version_.Get();
}
inline void KernelDistro::_internal_set_kernel_version(const std::string& value) {
  
  _impl_.kernel_version_.Set(value, GetArenaForAllocation());
}
inline std::string* KernelDistro::_internal_mutable_kernel_version() {
  
  return _impl_.kernel_version_.Mutable(GetArenaForAllocation());
}
inline std::string* KernelDistro::release_kernel_version() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.KernelDistro.kernel_version)
  return _impl_.kernel_version_.Release();
}
inline void KernelDistro::set_allocated_kernel_version(std::string* kernel_version) {
  if (kernel_version != nullptr) {
    
  } else {
    
  }
  _impl_.kernel_version_.SetAllocated(kernel_version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.kernel_version_.IsDefault()) {
    _impl_.kernel_version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.KernelDistro.kernel_version)
}

// string distro_name = 2;
inline void KernelDistro::clear_distro_name() {
  _impl_.distro_name_.ClearToEmpty();
}
inline const std::string& KernelDistro::distro_name() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.KernelDistro.distro_name)
  return _internal_distro_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KernelDistro::set_distro_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.distro_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.KernelDistro.distro_name)
}
inline std::string* KernelDistro::mutable_distro_name() {
  std::string* _s = _internal_mutable_distro_name();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.KernelDistro.distro_name)
  return _s;
}
inline const std::string& KernelDistro::_internal_distro_name() const {
  return _impl_.distro_name_.Get();
}
inline void KernelDistro::_internal_set_distro_name(const std::string& value) {
  
  _impl_.distro_name_.Set(value, GetArenaForAllocation());
}
inline std::string* KernelDistro::_internal_mutable_distro_name() {
  
  return _impl_.distro_name_.Mutable(GetArenaForAllocation());
}
inline std::string* KernelDistro::release_distro_name() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.KernelDistro.distro_name)
  return _impl_.distro_name_.Release();
}
inline void KernelDistro::set_allocated_distro_name(std::string* distro_name) {
  if (distro_name != nullptr) {
    
  } else {
    
  }
  _impl_.distro_name_.SetAllocated(distro_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.distro_name_.IsDefault()) {
    _impl_.distro_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.KernelDistro.distro_name)
}

// string hostip = 17;
inline void KernelDistro::clear_hostip() {
  _impl_.hostip_.ClearToEmpty();
}
inline const std::string& KernelDistro::hostip() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.KernelDistro.hostip)
  return _internal_hostip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void KernelDistro::set_hostip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.hostip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.KernelDistro.hostip)
}
inline std::string* KernelDistro::mutable_hostip() {
  std::string* _s = _internal_mutable_hostip();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.KernelDistro.hostip)
  return _s;
}
inline const std::string& KernelDistro::_internal_hostip() const {
  return _impl_.hostip_.Get();
}
inline void KernelDistro::_internal_set_hostip(const std::string& value) {
  
  _impl_.hostip_.Set(value, GetArenaForAllocation());
}
inline std::string* KernelDistro::_internal_mutable_hostip() {
  
  return _impl_.hostip_.Mutable(GetArenaForAllocation());
}
inline std::string* KernelDistro::release_hostip() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.KernelDistro.hostip)
  return _impl_.hostip_.Release();
}
inline void KernelDistro::set_allocated_hostip(std::string* hostip) {
  if (hostip != nullptr) {
    
  } else {
    
  }
  _impl_.hostip_.SetAllocated(hostip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.hostip_.IsDefault()) {
    _impl_.hostip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.KernelDistro.hostip)
}

// -------------------------------------------------------------------

// InstalledProgram

// string name = 1;
inline void InstalledProgram::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& InstalledProgram::name() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.InstalledProgram.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InstalledProgram::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.InstalledProgram.name)
}
inline std::string* InstalledProgram::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.InstalledProgram.name)
  return _s;
}
inline const std::string& InstalledProgram::_internal_name() const {
  return _impl_.name_.Get();
}
inline void InstalledProgram::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* InstalledProgram::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* InstalledProgram::release_name() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.InstalledProgram.name)
  return _impl_.name_.Release();
}
inline void InstalledProgram::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.InstalledProgram.name)
}

// string version = 2;
inline void InstalledProgram::clear_version() {
  _impl_.version_.ClearToEmpty();
}
inline const std::string& InstalledProgram::version() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.InstalledProgram.version)
  return _internal_version();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InstalledProgram::set_version(ArgT0&& arg0, ArgT... args) {
 
 _impl_.version_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.InstalledProgram.version)
}
inline std::string* InstalledProgram::mutable_version() {
  std::string* _s = _internal_mutable_version();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.InstalledProgram.version)
  return _s;
}
inline const std::string& InstalledProgram::_internal_version() const {
  return _impl_.version_.Get();
}
inline void InstalledProgram::_internal_set_version(const std::string& value) {
  
  _impl_.version_.Set(value, GetArenaForAllocation());
}
inline std::string* InstalledProgram::_internal_mutable_version() {
  
  return _impl_.version_.Mutable(GetArenaForAllocation());
}
inline std::string* InstalledProgram::release_version() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.InstalledProgram.version)
  return _impl_.version_.Release();
}
inline void InstalledProgram::set_allocated_version(std::string* version) {
  if (version != nullptr) {
    
  } else {
    
  }
  _impl_.version_.SetAllocated(version, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.version_.IsDefault()) {
    _impl_.version_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.InstalledProgram.version)
}

// -------------------------------------------------------------------

// InstalledProgramList

// string timestamp = 3;
inline void InstalledProgramList::clear_timestamp() {
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& InstalledProgramList::timestamp() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.InstalledProgramList.timestamp)
  return _internal_timestamp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InstalledProgramList::set_timestamp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timestamp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.InstalledProgramList.timestamp)
}
inline std::string* InstalledProgramList::mutable_timestamp() {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.InstalledProgramList.timestamp)
  return _s;
}
inline const std::string& InstalledProgramList::_internal_timestamp() const {
  return _impl_.timestamp_.Get();
}
inline void InstalledProgramList::_internal_set_timestamp(const std::string& value) {
  
  _impl_.timestamp_.Set(value, GetArenaForAllocation());
}
inline std::string* InstalledProgramList::_internal_mutable_timestamp() {
  
  return _impl_.timestamp_.Mutable(GetArenaForAllocation());
}
inline std::string* InstalledProgramList::release_timestamp() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.InstalledProgramList.timestamp)
  return _impl_.timestamp_.Release();
}
inline void InstalledProgramList::set_allocated_timestamp(std::string* timestamp) {
  if (timestamp != nullptr) {
    
  } else {
    
  }
  _impl_.timestamp_.SetAllocated(timestamp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.InstalledProgramList.timestamp)
}

// string hostip = 2;
inline void InstalledProgramList::clear_hostip() {
  _impl_.hostip_.ClearToEmpty();
}
inline const std::string& InstalledProgramList::hostip() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.InstalledProgramList.hostip)
  return _internal_hostip();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void InstalledProgramList::set_hostip(ArgT0&& arg0, ArgT... args) {
 
 _impl_.hostip_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.InstalledProgramList.hostip)
}
inline std::string* InstalledProgramList::mutable_hostip() {
  std::string* _s = _internal_mutable_hostip();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.InstalledProgramList.hostip)
  return _s;
}
inline const std::string& InstalledProgramList::_internal_hostip() const {
  return _impl_.hostip_.Get();
}
inline void InstalledProgramList::_internal_set_hostip(const std::string& value) {
  
  _impl_.hostip_.Set(value, GetArenaForAllocation());
}
inline std::string* InstalledProgramList::_internal_mutable_hostip() {
  
  return _impl_.hostip_.Mutable(GetArenaForAllocation());
}
inline std::string* InstalledProgramList::release_hostip() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.InstalledProgramList.hostip)
  return _impl_.hostip_.Release();
}
inline void InstalledProgramList::set_allocated_hostip(std::string* hostip) {
  if (hostip != nullptr) {
    
  } else {
    
  }
  _impl_.hostip_.SetAllocated(hostip, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.hostip_.IsDefault()) {
    _impl_.hostip_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.InstalledProgramList.hostip)
}

// repeated .ProcessMetricas.InstalledProgram programs = 1;
inline int InstalledProgramList::_internal_programs_size() const {
  return _impl_.programs_.size();
}
inline int InstalledProgramList::programs_size() const {
  return _internal_programs_size();
}
inline void InstalledProgramList::clear_programs() {
  _impl_.programs_.Clear();
}
inline ::ProcessMetricas::InstalledProgram* InstalledProgramList::mutable_programs(int index) {
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.InstalledProgramList.programs)
  return _impl_.programs_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::InstalledProgram >*
InstalledProgramList::mutable_programs() {
  // @@protoc_insertion_point(field_mutable_list:ProcessMetricas.InstalledProgramList.programs)
  return &_impl_.programs_;
}
inline const ::ProcessMetricas::InstalledProgram& InstalledProgramList::_internal_programs(int index) const {
  return _impl_.programs_.Get(index);
}
inline const ::ProcessMetricas::InstalledProgram& InstalledProgramList::programs(int index) const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.InstalledProgramList.programs)
  return _internal_programs(index);
}
inline ::ProcessMetricas::InstalledProgram* InstalledProgramList::_internal_add_programs() {
  return _impl_.programs_.Add();
}
inline ::ProcessMetricas::InstalledProgram* InstalledProgramList::add_programs() {
  ::ProcessMetricas::InstalledProgram* _add = _internal_add_programs();
  // @@protoc_insertion_point(field_add:ProcessMetricas.InstalledProgramList.programs)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::InstalledProgram >&
InstalledProgramList::programs() const {
  // @@protoc_insertion_point(field_list:ProcessMetricas.InstalledProgramList.programs)
  return _impl_.programs_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProcessMetricas

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ProcessMetricas_2eproto
