// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProcessMetricas.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_ProcessMetricas_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_ProcessMetricas_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_ProcessMetricas_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_ProcessMetricas_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_ProcessMetricas_2eproto;
namespace ProcessMetricas {
class ProcessMetrics;
struct ProcessMetricsDefaultTypeInternal;
extern ProcessMetricsDefaultTypeInternal _ProcessMetrics_default_instance_;
class ProcessMetricsList;
struct ProcessMetricsListDefaultTypeInternal;
extern ProcessMetricsListDefaultTypeInternal _ProcessMetricsList_default_instance_;
}  // namespace ProcessMetricas
PROTOBUF_NAMESPACE_OPEN
template<> ::ProcessMetricas::ProcessMetrics* Arena::CreateMaybeMessage<::ProcessMetricas::ProcessMetrics>(Arena*);
template<> ::ProcessMetricas::ProcessMetricsList* Arena::CreateMaybeMessage<::ProcessMetricas::ProcessMetricsList>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace ProcessMetricas {

// ===================================================================

class ProcessMetrics final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProcessMetricas.ProcessMetrics) */ {
 public:
  inline ProcessMetrics() : ProcessMetrics(nullptr) {}
  ~ProcessMetrics() override;
  explicit PROTOBUF_CONSTEXPR ProcessMetrics(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProcessMetrics(const ProcessMetrics& from);
  ProcessMetrics(ProcessMetrics&& from) noexcept
    : ProcessMetrics() {
    *this = ::std::move(from);
  }

  inline ProcessMetrics& operator=(const ProcessMetrics& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProcessMetrics& operator=(ProcessMetrics&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProcessMetrics& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProcessMetrics* internal_default_instance() {
    return reinterpret_cast<const ProcessMetrics*>(
               &_ProcessMetrics_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ProcessMetrics& a, ProcessMetrics& b) {
    a.Swap(&b);
  }
  inline void Swap(ProcessMetrics* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProcessMetrics* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProcessMetrics* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProcessMetrics>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProcessMetrics& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProcessMetrics& from) {
    ProcessMetrics::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProcessMetrics* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProcessMetricas.ProcessMetrics";
  }
  protected:
  explicit ProcessMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kNameFieldNumber = 2,
    kUserFieldNumber = 3,
    kTimestampFieldNumber = 4,
    kStatusFieldNumber = 5,
    kPidFieldNumber = 1,
    kNumThreadsFieldNumber = 7,
    kCreateTimeFieldNumber = 6,
    kCpuPercentFieldNumber = 8,
    kNumChildProcessesFieldNumber = 9,
    kReadBytesFieldNumber = 11,
    kMemoryPercentFieldNumber = 10,
    kNumFdsFieldNumber = 13,
    kWriteBytesFieldNumber = 12,
    kNiceFieldNumber = 14,
  };
  // string name = 2;
  void clear_name();
  const std::string& name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* name);
  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // string user = 3;
  void clear_user();
  const std::string& user() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_user(ArgT0&& arg0, ArgT... args);
  std::string* mutable_user();
  PROTOBUF_NODISCARD std::string* release_user();
  void set_allocated_user(std::string* user);
  private:
  const std::string& _internal_user() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_user(const std::string& value);
  std::string* _internal_mutable_user();
  public:

  // string timestamp = 4;
  void clear_timestamp();
  const std::string& timestamp() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_timestamp(ArgT0&& arg0, ArgT... args);
  std::string* mutable_timestamp();
  PROTOBUF_NODISCARD std::string* release_timestamp();
  void set_allocated_timestamp(std::string* timestamp);
  private:
  const std::string& _internal_timestamp() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_timestamp(const std::string& value);
  std::string* _internal_mutable_timestamp();
  public:

  // string status = 5;
  void clear_status();
  const std::string& status() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_status(ArgT0&& arg0, ArgT... args);
  std::string* mutable_status();
  PROTOBUF_NODISCARD std::string* release_status();
  void set_allocated_status(std::string* status);
  private:
  const std::string& _internal_status() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_status(const std::string& value);
  std::string* _internal_mutable_status();
  public:

  // int32 pid = 1;
  void clear_pid();
  int32_t pid() const;
  void set_pid(int32_t value);
  private:
  int32_t _internal_pid() const;
  void _internal_set_pid(int32_t value);
  public:

  // int32 num_threads = 7;
  void clear_num_threads();
  int32_t num_threads() const;
  void set_num_threads(int32_t value);
  private:
  int32_t _internal_num_threads() const;
  void _internal_set_num_threads(int32_t value);
  public:

  // double create_time = 6;
  void clear_create_time();
  double create_time() const;
  void set_create_time(double value);
  private:
  double _internal_create_time() const;
  void _internal_set_create_time(double value);
  public:

  // float cpu_percent = 8;
  void clear_cpu_percent();
  float cpu_percent() const;
  void set_cpu_percent(float value);
  private:
  float _internal_cpu_percent() const;
  void _internal_set_cpu_percent(float value);
  public:

  // int32 num_child_processes = 9;
  void clear_num_child_processes();
  int32_t num_child_processes() const;
  void set_num_child_processes(int32_t value);
  private:
  int32_t _internal_num_child_processes() const;
  void _internal_set_num_child_processes(int32_t value);
  public:

  // uint64 read_bytes = 11;
  void clear_read_bytes();
  uint64_t read_bytes() const;
  void set_read_bytes(uint64_t value);
  private:
  uint64_t _internal_read_bytes() const;
  void _internal_set_read_bytes(uint64_t value);
  public:

  // float memory_percent = 10;
  void clear_memory_percent();
  float memory_percent() const;
  void set_memory_percent(float value);
  private:
  float _internal_memory_percent() const;
  void _internal_set_memory_percent(float value);
  public:

  // int32 num_fds = 13;
  void clear_num_fds();
  int32_t num_fds() const;
  void set_num_fds(int32_t value);
  private:
  int32_t _internal_num_fds() const;
  void _internal_set_num_fds(int32_t value);
  public:

  // uint64 write_bytes = 12;
  void clear_write_bytes();
  uint64_t write_bytes() const;
  void set_write_bytes(uint64_t value);
  private:
  uint64_t _internal_write_bytes() const;
  void _internal_set_write_bytes(uint64_t value);
  public:

  // int32 nice = 14;
  void clear_nice();
  int32_t nice() const;
  void set_nice(int32_t value);
  private:
  int32_t _internal_nice() const;
  void _internal_set_nice(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:ProcessMetricas.ProcessMetrics)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr user_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr timestamp_;
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr status_;
    int32_t pid_;
    int32_t num_threads_;
    double create_time_;
    float cpu_percent_;
    int32_t num_child_processes_;
    uint64_t read_bytes_;
    float memory_percent_;
    int32_t num_fds_;
    uint64_t write_bytes_;
    int32_t nice_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProcessMetricas_2eproto;
};
// -------------------------------------------------------------------

class ProcessMetricsList final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:ProcessMetricas.ProcessMetricsList) */ {
 public:
  inline ProcessMetricsList() : ProcessMetricsList(nullptr) {}
  ~ProcessMetricsList() override;
  explicit PROTOBUF_CONSTEXPR ProcessMetricsList(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ProcessMetricsList(const ProcessMetricsList& from);
  ProcessMetricsList(ProcessMetricsList&& from) noexcept
    : ProcessMetricsList() {
    *this = ::std::move(from);
  }

  inline ProcessMetricsList& operator=(const ProcessMetricsList& from) {
    CopyFrom(from);
    return *this;
  }
  inline ProcessMetricsList& operator=(ProcessMetricsList&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ProcessMetricsList& default_instance() {
    return *internal_default_instance();
  }
  static inline const ProcessMetricsList* internal_default_instance() {
    return reinterpret_cast<const ProcessMetricsList*>(
               &_ProcessMetricsList_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ProcessMetricsList& a, ProcessMetricsList& b) {
    a.Swap(&b);
  }
  inline void Swap(ProcessMetricsList* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ProcessMetricsList* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ProcessMetricsList* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ProcessMetricsList>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ProcessMetricsList& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ProcessMetricsList& from) {
    ProcessMetricsList::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ProcessMetricsList* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "ProcessMetricas.ProcessMetricsList";
  }
  protected:
  explicit ProcessMetricsList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kProcessesFieldNumber = 1,
  };
  // repeated .ProcessMetricas.ProcessMetrics processes = 1;
  int processes_size() const;
  private:
  int _internal_processes_size() const;
  public:
  void clear_processes();
  ::ProcessMetricas::ProcessMetrics* mutable_processes(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::ProcessMetrics >*
      mutable_processes();
  private:
  const ::ProcessMetricas::ProcessMetrics& _internal_processes(int index) const;
  ::ProcessMetricas::ProcessMetrics* _internal_add_processes();
  public:
  const ::ProcessMetricas::ProcessMetrics& processes(int index) const;
  ::ProcessMetricas::ProcessMetrics* add_processes();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::ProcessMetrics >&
      processes() const;

  // @@protoc_insertion_point(class_scope:ProcessMetricas.ProcessMetricsList)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::ProcessMetrics > processes_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_ProcessMetricas_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ProcessMetrics

// int32 pid = 1;
inline void ProcessMetrics::clear_pid() {
  _impl_.pid_ = 0;
}
inline int32_t ProcessMetrics::_internal_pid() const {
  return _impl_.pid_;
}
inline int32_t ProcessMetrics::pid() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.pid)
  return _internal_pid();
}
inline void ProcessMetrics::_internal_set_pid(int32_t value) {
  
  _impl_.pid_ = value;
}
inline void ProcessMetrics::set_pid(int32_t value) {
  _internal_set_pid(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.pid)
}

// string name = 2;
inline void ProcessMetrics::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& ProcessMetrics::name() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.name)
  return _internal_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProcessMetrics::set_name(ArgT0&& arg0, ArgT... args) {
 
 _impl_.name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.name)
}
inline std::string* ProcessMetrics::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.ProcessMetrics.name)
  return _s;
}
inline const std::string& ProcessMetrics::_internal_name() const {
  return _impl_.name_.Get();
}
inline void ProcessMetrics::_internal_set_name(const std::string& value) {
  
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* ProcessMetrics::_internal_mutable_name() {
  
  return _impl_.name_.Mutable(GetArenaForAllocation());
}
inline std::string* ProcessMetrics::release_name() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.ProcessMetrics.name)
  return _impl_.name_.Release();
}
inline void ProcessMetrics::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  _impl_.name_.SetAllocated(name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.ProcessMetrics.name)
}

// string user = 3;
inline void ProcessMetrics::clear_user() {
  _impl_.user_.ClearToEmpty();
}
inline const std::string& ProcessMetrics::user() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.user)
  return _internal_user();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProcessMetrics::set_user(ArgT0&& arg0, ArgT... args) {
 
 _impl_.user_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.user)
}
inline std::string* ProcessMetrics::mutable_user() {
  std::string* _s = _internal_mutable_user();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.ProcessMetrics.user)
  return _s;
}
inline const std::string& ProcessMetrics::_internal_user() const {
  return _impl_.user_.Get();
}
inline void ProcessMetrics::_internal_set_user(const std::string& value) {
  
  _impl_.user_.Set(value, GetArenaForAllocation());
}
inline std::string* ProcessMetrics::_internal_mutable_user() {
  
  return _impl_.user_.Mutable(GetArenaForAllocation());
}
inline std::string* ProcessMetrics::release_user() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.ProcessMetrics.user)
  return _impl_.user_.Release();
}
inline void ProcessMetrics::set_allocated_user(std::string* user) {
  if (user != nullptr) {
    
  } else {
    
  }
  _impl_.user_.SetAllocated(user, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.user_.IsDefault()) {
    _impl_.user_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.ProcessMetrics.user)
}

// string timestamp = 4;
inline void ProcessMetrics::clear_timestamp() {
  _impl_.timestamp_.ClearToEmpty();
}
inline const std::string& ProcessMetrics::timestamp() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.timestamp)
  return _internal_timestamp();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProcessMetrics::set_timestamp(ArgT0&& arg0, ArgT... args) {
 
 _impl_.timestamp_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.timestamp)
}
inline std::string* ProcessMetrics::mutable_timestamp() {
  std::string* _s = _internal_mutable_timestamp();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.ProcessMetrics.timestamp)
  return _s;
}
inline const std::string& ProcessMetrics::_internal_timestamp() const {
  return _impl_.timestamp_.Get();
}
inline void ProcessMetrics::_internal_set_timestamp(const std::string& value) {
  
  _impl_.timestamp_.Set(value, GetArenaForAllocation());
}
inline std::string* ProcessMetrics::_internal_mutable_timestamp() {
  
  return _impl_.timestamp_.Mutable(GetArenaForAllocation());
}
inline std::string* ProcessMetrics::release_timestamp() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.ProcessMetrics.timestamp)
  return _impl_.timestamp_.Release();
}
inline void ProcessMetrics::set_allocated_timestamp(std::string* timestamp) {
  if (timestamp != nullptr) {
    
  } else {
    
  }
  _impl_.timestamp_.SetAllocated(timestamp, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.timestamp_.IsDefault()) {
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.ProcessMetrics.timestamp)
}

// string status = 5;
inline void ProcessMetrics::clear_status() {
  _impl_.status_.ClearToEmpty();
}
inline const std::string& ProcessMetrics::status() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.status)
  return _internal_status();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void ProcessMetrics::set_status(ArgT0&& arg0, ArgT... args) {
 
 _impl_.status_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.status)
}
inline std::string* ProcessMetrics::mutable_status() {
  std::string* _s = _internal_mutable_status();
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.ProcessMetrics.status)
  return _s;
}
inline const std::string& ProcessMetrics::_internal_status() const {
  return _impl_.status_.Get();
}
inline void ProcessMetrics::_internal_set_status(const std::string& value) {
  
  _impl_.status_.Set(value, GetArenaForAllocation());
}
inline std::string* ProcessMetrics::_internal_mutable_status() {
  
  return _impl_.status_.Mutable(GetArenaForAllocation());
}
inline std::string* ProcessMetrics::release_status() {
  // @@protoc_insertion_point(field_release:ProcessMetricas.ProcessMetrics.status)
  return _impl_.status_.Release();
}
inline void ProcessMetrics::set_allocated_status(std::string* status) {
  if (status != nullptr) {
    
  } else {
    
  }
  _impl_.status_.SetAllocated(status, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.status_.IsDefault()) {
    _impl_.status_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:ProcessMetricas.ProcessMetrics.status)
}

// double create_time = 6;
inline void ProcessMetrics::clear_create_time() {
  _impl_.create_time_ = 0;
}
inline double ProcessMetrics::_internal_create_time() const {
  return _impl_.create_time_;
}
inline double ProcessMetrics::create_time() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.create_time)
  return _internal_create_time();
}
inline void ProcessMetrics::_internal_set_create_time(double value) {
  
  _impl_.create_time_ = value;
}
inline void ProcessMetrics::set_create_time(double value) {
  _internal_set_create_time(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.create_time)
}

// int32 num_threads = 7;
inline void ProcessMetrics::clear_num_threads() {
  _impl_.num_threads_ = 0;
}
inline int32_t ProcessMetrics::_internal_num_threads() const {
  return _impl_.num_threads_;
}
inline int32_t ProcessMetrics::num_threads() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.num_threads)
  return _internal_num_threads();
}
inline void ProcessMetrics::_internal_set_num_threads(int32_t value) {
  
  _impl_.num_threads_ = value;
}
inline void ProcessMetrics::set_num_threads(int32_t value) {
  _internal_set_num_threads(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.num_threads)
}

// float cpu_percent = 8;
inline void ProcessMetrics::clear_cpu_percent() {
  _impl_.cpu_percent_ = 0;
}
inline float ProcessMetrics::_internal_cpu_percent() const {
  return _impl_.cpu_percent_;
}
inline float ProcessMetrics::cpu_percent() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.cpu_percent)
  return _internal_cpu_percent();
}
inline void ProcessMetrics::_internal_set_cpu_percent(float value) {
  
  _impl_.cpu_percent_ = value;
}
inline void ProcessMetrics::set_cpu_percent(float value) {
  _internal_set_cpu_percent(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.cpu_percent)
}

// int32 num_child_processes = 9;
inline void ProcessMetrics::clear_num_child_processes() {
  _impl_.num_child_processes_ = 0;
}
inline int32_t ProcessMetrics::_internal_num_child_processes() const {
  return _impl_.num_child_processes_;
}
inline int32_t ProcessMetrics::num_child_processes() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.num_child_processes)
  return _internal_num_child_processes();
}
inline void ProcessMetrics::_internal_set_num_child_processes(int32_t value) {
  
  _impl_.num_child_processes_ = value;
}
inline void ProcessMetrics::set_num_child_processes(int32_t value) {
  _internal_set_num_child_processes(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.num_child_processes)
}

// float memory_percent = 10;
inline void ProcessMetrics::clear_memory_percent() {
  _impl_.memory_percent_ = 0;
}
inline float ProcessMetrics::_internal_memory_percent() const {
  return _impl_.memory_percent_;
}
inline float ProcessMetrics::memory_percent() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.memory_percent)
  return _internal_memory_percent();
}
inline void ProcessMetrics::_internal_set_memory_percent(float value) {
  
  _impl_.memory_percent_ = value;
}
inline void ProcessMetrics::set_memory_percent(float value) {
  _internal_set_memory_percent(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.memory_percent)
}

// uint64 read_bytes = 11;
inline void ProcessMetrics::clear_read_bytes() {
  _impl_.read_bytes_ = uint64_t{0u};
}
inline uint64_t ProcessMetrics::_internal_read_bytes() const {
  return _impl_.read_bytes_;
}
inline uint64_t ProcessMetrics::read_bytes() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.read_bytes)
  return _internal_read_bytes();
}
inline void ProcessMetrics::_internal_set_read_bytes(uint64_t value) {
  
  _impl_.read_bytes_ = value;
}
inline void ProcessMetrics::set_read_bytes(uint64_t value) {
  _internal_set_read_bytes(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.read_bytes)
}

// uint64 write_bytes = 12;
inline void ProcessMetrics::clear_write_bytes() {
  _impl_.write_bytes_ = uint64_t{0u};
}
inline uint64_t ProcessMetrics::_internal_write_bytes() const {
  return _impl_.write_bytes_;
}
inline uint64_t ProcessMetrics::write_bytes() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.write_bytes)
  return _internal_write_bytes();
}
inline void ProcessMetrics::_internal_set_write_bytes(uint64_t value) {
  
  _impl_.write_bytes_ = value;
}
inline void ProcessMetrics::set_write_bytes(uint64_t value) {
  _internal_set_write_bytes(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.write_bytes)
}

// int32 num_fds = 13;
inline void ProcessMetrics::clear_num_fds() {
  _impl_.num_fds_ = 0;
}
inline int32_t ProcessMetrics::_internal_num_fds() const {
  return _impl_.num_fds_;
}
inline int32_t ProcessMetrics::num_fds() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.num_fds)
  return _internal_num_fds();
}
inline void ProcessMetrics::_internal_set_num_fds(int32_t value) {
  
  _impl_.num_fds_ = value;
}
inline void ProcessMetrics::set_num_fds(int32_t value) {
  _internal_set_num_fds(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.num_fds)
}

// int32 nice = 14;
inline void ProcessMetrics::clear_nice() {
  _impl_.nice_ = 0;
}
inline int32_t ProcessMetrics::_internal_nice() const {
  return _impl_.nice_;
}
inline int32_t ProcessMetrics::nice() const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetrics.nice)
  return _internal_nice();
}
inline void ProcessMetrics::_internal_set_nice(int32_t value) {
  
  _impl_.nice_ = value;
}
inline void ProcessMetrics::set_nice(int32_t value) {
  _internal_set_nice(value);
  // @@protoc_insertion_point(field_set:ProcessMetricas.ProcessMetrics.nice)
}

// -------------------------------------------------------------------

// ProcessMetricsList

// repeated .ProcessMetricas.ProcessMetrics processes = 1;
inline int ProcessMetricsList::_internal_processes_size() const {
  return _impl_.processes_.size();
}
inline int ProcessMetricsList::processes_size() const {
  return _internal_processes_size();
}
inline void ProcessMetricsList::clear_processes() {
  _impl_.processes_.Clear();
}
inline ::ProcessMetricas::ProcessMetrics* ProcessMetricsList::mutable_processes(int index) {
  // @@protoc_insertion_point(field_mutable:ProcessMetricas.ProcessMetricsList.processes)
  return _impl_.processes_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::ProcessMetrics >*
ProcessMetricsList::mutable_processes() {
  // @@protoc_insertion_point(field_mutable_list:ProcessMetricas.ProcessMetricsList.processes)
  return &_impl_.processes_;
}
inline const ::ProcessMetricas::ProcessMetrics& ProcessMetricsList::_internal_processes(int index) const {
  return _impl_.processes_.Get(index);
}
inline const ::ProcessMetricas::ProcessMetrics& ProcessMetricsList::processes(int index) const {
  // @@protoc_insertion_point(field_get:ProcessMetricas.ProcessMetricsList.processes)
  return _internal_processes(index);
}
inline ::ProcessMetricas::ProcessMetrics* ProcessMetricsList::_internal_add_processes() {
  return _impl_.processes_.Add();
}
inline ::ProcessMetricas::ProcessMetrics* ProcessMetricsList::add_processes() {
  ::ProcessMetricas::ProcessMetrics* _add = _internal_add_processes();
  // @@protoc_insertion_point(field_add:ProcessMetricas.ProcessMetricsList.processes)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::ProcessMetricas::ProcessMetrics >&
ProcessMetricsList::processes() const {
  // @@protoc_insertion_point(field_list:ProcessMetricas.ProcessMetricsList.processes)
  return _impl_.processes_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace ProcessMetricas

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_ProcessMetricas_2eproto
