// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProcessMetricas.proto

#include "ProcessMetricas.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG

namespace _pb = ::PROTOBUF_NAMESPACE_ID;
namespace _pbi = _pb::internal;

namespace ProcessMetricas {
PROTOBUF_CONSTEXPR ProcessMetrics::ProcessMetrics(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_._has_bits_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}
  , /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.user_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.boottime_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestartprocess_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.hostip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.pid_)*/0
  , /*decltype(_impl_.num_threads_)*/0
  , /*decltype(_impl_.cpu_percent_)*/0
  , /*decltype(_impl_.num_child_processes_)*/0
  , /*decltype(_impl_.read_bytes_kb_)*/uint64_t{0u}
  , /*decltype(_impl_.memory_percent_)*/0
  , /*decltype(_impl_.num_fds_)*/0
  , /*decltype(_impl_.write_bytes_kb_)*/uint64_t{0u}
  , /*decltype(_impl_.nice_)*/0
  , /*decltype(_impl_.ionice_value_)*/0
  , /*decltype(_impl_.gid_effective_)*/0
  , /*decltype(_impl_.mem_rss_kb_)*/0
  , /*decltype(_impl_.mem_shared_kb_)*/0
  , /*decltype(_impl_.mem_vms_kb_)*/0
  , /*decltype(_impl_.mem_text_kb_)*/0} {}
struct ProcessMetricsDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessMetricsDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessMetricsDefaultTypeInternal() {}
  union {
    ProcessMetrics _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessMetricsDefaultTypeInternal _ProcessMetrics_default_instance_;
PROTOBUF_CONSTEXPR ProcessMetricsList::ProcessMetricsList(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.processes_)*/{}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct ProcessMetricsListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ProcessMetricsListDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ProcessMetricsListDefaultTypeInternal() {}
  union {
    ProcessMetricsList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ProcessMetricsListDefaultTypeInternal _ProcessMetricsList_default_instance_;
PROTOBUF_CONSTEXPR KernelDistro::KernelDistro(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.kernel_version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.distro_name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.hostip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct KernelDistroDefaultTypeInternal {
  PROTOBUF_CONSTEXPR KernelDistroDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~KernelDistroDefaultTypeInternal() {}
  union {
    KernelDistro _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 KernelDistroDefaultTypeInternal _KernelDistro_default_instance_;
PROTOBUF_CONSTEXPR InstalledProgram::InstalledProgram(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.name_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.version_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InstalledProgramDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InstalledProgramDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InstalledProgramDefaultTypeInternal() {}
  union {
    InstalledProgram _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InstalledProgramDefaultTypeInternal _InstalledProgram_default_instance_;
PROTOBUF_CONSTEXPR InstalledProgramList::InstalledProgramList(
    ::_pbi::ConstantInitialized): _impl_{
    /*decltype(_impl_.programs_)*/{}
  , /*decltype(_impl_.hostip_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_.timestamp_)*/{&::_pbi::fixed_address_empty_string, ::_pbi::ConstantInitialized{}}
  , /*decltype(_impl_._cached_size_)*/{}} {}
struct InstalledProgramListDefaultTypeInternal {
  PROTOBUF_CONSTEXPR InstalledProgramListDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~InstalledProgramListDefaultTypeInternal() {}
  union {
    InstalledProgramList _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 InstalledProgramListDefaultTypeInternal _InstalledProgramList_default_instance_;
}  // namespace ProcessMetricas
static ::_pb::Metadata file_level_metadata_ProcessMetricas_2eproto[5];
static constexpr ::_pb::EnumDescriptor const** file_level_enum_descriptors_ProcessMetricas_2eproto = nullptr;
static constexpr ::_pb::ServiceDescriptor const** file_level_service_descriptors_ProcessMetricas_2eproto = nullptr;

const uint32_t TableStruct_ProcessMetricas_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_._has_bits_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.pid_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.user_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.num_threads_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.num_child_processes_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.cpu_percent_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.memory_percent_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.mem_rss_kb_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.mem_shared_kb_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.mem_vms_kb_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.mem_text_kb_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.read_bytes_kb_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.write_bytes_kb_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.num_fds_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.nice_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.ionice_value_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.boottime_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.timestartprocess_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.hostip_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetrics, _impl_.gid_effective_),
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  1,
  0,
  3,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  2,
  5,
  4,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetricsList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::ProcessMetricsList, _impl_.processes_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::KernelDistro, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::KernelDistro, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::KernelDistro, _impl_.kernel_version_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::KernelDistro, _impl_.distro_name_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::KernelDistro, _impl_.hostip_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::InstalledProgram, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::InstalledProgram, _impl_.name_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::InstalledProgram, _impl_.version_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::InstalledProgramList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  ~0u,  // no _inlined_string_donated_
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::InstalledProgramList, _impl_.timestamp_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::InstalledProgramList, _impl_.hostip_),
  PROTOBUF_FIELD_OFFSET(::ProcessMetricas::InstalledProgramList, _impl_.programs_),
};
static const ::_pbi::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 27, -1, sizeof(::ProcessMetricas::ProcessMetrics)},
  { 48, -1, -1, sizeof(::ProcessMetricas::ProcessMetricsList)},
  { 55, -1, -1, sizeof(::ProcessMetricas::KernelDistro)},
  { 65, -1, -1, sizeof(::ProcessMetricas::InstalledProgram)},
  { 73, -1, -1, sizeof(::ProcessMetricas::InstalledProgramList)},
};

static const ::_pb::Message* const file_default_instances[] = {
  &::ProcessMetricas::_ProcessMetrics_default_instance_._instance,
  &::ProcessMetricas::_ProcessMetricsList_default_instance_._instance,
  &::ProcessMetricas::_KernelDistro_default_instance_._instance,
  &::ProcessMetricas::_InstalledProgram_default_instance_._instance,
  &::ProcessMetricas::_InstalledProgramList_default_instance_._instance,
};

const char descriptor_table_protodef_ProcessMetricas_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\025ProcessMetricas.proto\022\017ProcessMetricas"
  "\"\300\004\n\016ProcessMetrics\022\013\n\003pid\030\001 \001(\005\022\014\n\004name"
  "\030\002 \001(\t\022\014\n\004user\030\003 \001(\t\022\023\n\013num_threads\030\007 \001("
  "\005\022 \n\023num_child_processes\030\t \001(\005H\000\210\001\001\022\030\n\013c"
  "pu_percent\030\010 \001(\002H\001\210\001\001\022\033\n\016memory_percent\030"
  "\n \001(\002H\002\210\001\001\022\022\n\nmem_rss_kb\030\027 \001(\005\022\025\n\rmem_sh"
  "ared_kb\030\031 \001(\005\022\022\n\nmem_vms_kb\030\032 \001(\005\022\023\n\013mem"
  "_text_kb\030\033 \001(\005\022\032\n\rread_bytes_kb\030\013 \001(\004H\003\210"
  "\001\001\022\033\n\016write_bytes_kb\030\014 \001(\004H\004\210\001\001\022\024\n\007num_f"
  "ds\030\r \001(\005H\005\210\001\001\022\014\n\004nice\030\016 \001(\005\022\024\n\014ionice_va"
  "lue\030\024 \001(\005\022\021\n\ttimestamp\030\004 \001(\t\022\020\n\010boottime"
  "\030\017 \001(\t\022\030\n\020timestartprocess\030\020 \001(\t\022\016\n\006host"
  "ip\030\021 \001(\t\022\025\n\rgid_effective\030\025 \001(\005B\026\n\024_num_"
  "child_processesB\016\n\014_cpu_percentB\021\n\017_memo"
  "ry_percentB\020\n\016_read_bytes_kbB\021\n\017_write_b"
  "ytes_kbB\n\n\010_num_fds\"H\n\022ProcessMetricsLis"
  "t\0222\n\tprocesses\030\001 \003(\0132\037.ProcessMetricas.P"
  "rocessMetrics\"^\n\014KernelDistro\022\021\n\ttimesta"
  "mp\030\003 \001(\t\022\026\n\016kernel_version\030\001 \001(\t\022\023\n\013dist"
  "ro_name\030\002 \001(\t\022\016\n\006hostip\030\021 \001(\t\"1\n\020Install"
  "edProgram\022\014\n\004name\030\001 \001(\t\022\017\n\007version\030\002 \001(\t"
  "\"n\n\024InstalledProgramList\022\021\n\ttimestamp\030\003 "
  "\001(\t\022\016\n\006hostip\030\002 \001(\t\0223\n\010programs\030\001 \003(\0132!."
  "ProcessMetricas.InstalledProgramb\006proto3"
  ;
static ::_pbi::once_flag descriptor_table_ProcessMetricas_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_ProcessMetricas_2eproto = {
    false, false, 960, descriptor_table_protodef_ProcessMetricas_2eproto,
    "ProcessMetricas.proto",
    &descriptor_table_ProcessMetricas_2eproto_once, nullptr, 0, 5,
    schemas, file_default_instances, TableStruct_ProcessMetricas_2eproto::offsets,
    file_level_metadata_ProcessMetricas_2eproto, file_level_enum_descriptors_ProcessMetricas_2eproto,
    file_level_service_descriptors_ProcessMetricas_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_ProcessMetricas_2eproto_getter() {
  return &descriptor_table_ProcessMetricas_2eproto;
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_ProcessMetricas_2eproto(&descriptor_table_ProcessMetricas_2eproto);
namespace ProcessMetricas {

// ===================================================================

class ProcessMetrics::_Internal {
 public:
  using HasBits = decltype(std::declval<ProcessMetrics>()._impl_._has_bits_);
  static void set_has_num_child_processes(HasBits* has_bits) {
    (*has_bits)[0] |= 2u;
  }
  static void set_has_cpu_percent(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
  static void set_has_memory_percent(HasBits* has_bits) {
    (*has_bits)[0] |= 8u;
  }
  static void set_has_read_bytes_kb(HasBits* has_bits) {
    (*has_bits)[0] |= 4u;
  }
  static void set_has_write_bytes_kb(HasBits* has_bits) {
    (*has_bits)[0] |= 32u;
  }
  static void set_has_num_fds(HasBits* has_bits) {
    (*has_bits)[0] |= 16u;
  }
};

ProcessMetrics::ProcessMetrics(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ProcessMetricas.ProcessMetrics)
}
ProcessMetrics::ProcessMetrics(const ProcessMetrics& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProcessMetrics* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.name_){}
    , decltype(_impl_.user_){}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.boottime_){}
    , decltype(_impl_.timestartprocess_){}
    , decltype(_impl_.hostip_){}
    , decltype(_impl_.pid_){}
    , decltype(_impl_.num_threads_){}
    , decltype(_impl_.cpu_percent_){}
    , decltype(_impl_.num_child_processes_){}
    , decltype(_impl_.read_bytes_kb_){}
    , decltype(_impl_.memory_percent_){}
    , decltype(_impl_.num_fds_){}
    , decltype(_impl_.write_bytes_kb_){}
    , decltype(_impl_.nice_){}
    , decltype(_impl_.ionice_value_){}
    , decltype(_impl_.gid_effective_){}
    , decltype(_impl_.mem_rss_kb_){}
    , decltype(_impl_.mem_shared_kb_){}
    , decltype(_impl_.mem_vms_kb_){}
    , decltype(_impl_.mem_text_kb_){}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.user_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_user().empty()) {
    _this->_impl_.user_.Set(from._internal_user(), 
      _this->GetArenaForAllocation());
  }
  _impl_.timestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_timestamp().empty()) {
    _this->_impl_.timestamp_.Set(from._internal_timestamp(), 
      _this->GetArenaForAllocation());
  }
  _impl_.boottime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.boottime_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_boottime().empty()) {
    _this->_impl_.boottime_.Set(from._internal_boottime(), 
      _this->GetArenaForAllocation());
  }
  _impl_.timestartprocess_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestartprocess_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_timestartprocess().empty()) {
    _this->_impl_.timestartprocess_.Set(from._internal_timestartprocess(), 
      _this->GetArenaForAllocation());
  }
  _impl_.hostip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hostip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_hostip().empty()) {
    _this->_impl_.hostip_.Set(from._internal_hostip(), 
      _this->GetArenaForAllocation());
  }
  ::memcpy(&_impl_.pid_, &from._impl_.pid_,
    static_cast<size_t>(reinterpret_cast<char*>(&_impl_.mem_text_kb_) -
    reinterpret_cast<char*>(&_impl_.pid_)) + sizeof(_impl_.mem_text_kb_));
  // @@protoc_insertion_point(copy_constructor:ProcessMetricas.ProcessMetrics)
}

inline void ProcessMetrics::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){}
    , /*decltype(_impl_._cached_size_)*/{}
    , decltype(_impl_.name_){}
    , decltype(_impl_.user_){}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.boottime_){}
    , decltype(_impl_.timestartprocess_){}
    , decltype(_impl_.hostip_){}
    , decltype(_impl_.pid_){0}
    , decltype(_impl_.num_threads_){0}
    , decltype(_impl_.cpu_percent_){0}
    , decltype(_impl_.num_child_processes_){0}
    , decltype(_impl_.read_bytes_kb_){uint64_t{0u}}
    , decltype(_impl_.memory_percent_){0}
    , decltype(_impl_.num_fds_){0}
    , decltype(_impl_.write_bytes_kb_){uint64_t{0u}}
    , decltype(_impl_.nice_){0}
    , decltype(_impl_.ionice_value_){0}
    , decltype(_impl_.gid_effective_){0}
    , decltype(_impl_.mem_rss_kb_){0}
    , decltype(_impl_.mem_shared_kb_){0}
    , decltype(_impl_.mem_vms_kb_){0}
    , decltype(_impl_.mem_text_kb_){0}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.user_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.user_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.timestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.boottime_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.boottime_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.timestartprocess_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestartprocess_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.hostip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hostip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

ProcessMetrics::~ProcessMetrics() {
  // @@protoc_insertion_point(destructor:ProcessMetricas.ProcessMetrics)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProcessMetrics::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  _impl_.user_.Destroy();
  _impl_.timestamp_.Destroy();
  _impl_.boottime_.Destroy();
  _impl_.timestartprocess_.Destroy();
  _impl_.hostip_.Destroy();
}

void ProcessMetrics::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProcessMetrics::Clear() {
// @@protoc_insertion_point(message_clear_start:ProcessMetricas.ProcessMetrics)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.user_.ClearToEmpty();
  _impl_.timestamp_.ClearToEmpty();
  _impl_.boottime_.ClearToEmpty();
  _impl_.timestartprocess_.ClearToEmpty();
  _impl_.hostip_.ClearToEmpty();
  ::memset(&_impl_.pid_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.num_threads_) -
      reinterpret_cast<char*>(&_impl_.pid_)) + sizeof(_impl_.num_threads_));
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    ::memset(&_impl_.cpu_percent_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&_impl_.write_bytes_kb_) -
        reinterpret_cast<char*>(&_impl_.cpu_percent_)) + sizeof(_impl_.write_bytes_kb_));
  }
  ::memset(&_impl_.nice_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&_impl_.mem_text_kb_) -
      reinterpret_cast<char*>(&_impl_.nice_)) + sizeof(_impl_.mem_text_kb_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProcessMetrics::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  _Internal::HasBits has_bits{};
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // int32 pid = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 8)) {
          _impl_.pid_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.ProcessMetrics.name"));
        } else
          goto handle_unusual;
        continue;
      // string user = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_user();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.ProcessMetrics.user"));
        } else
          goto handle_unusual;
        continue;
      // string timestamp = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 34)) {
          auto str = _internal_mutable_timestamp();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.ProcessMetrics.timestamp"));
        } else
          goto handle_unusual;
        continue;
      // int32 num_threads = 7;
      case 7:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 56)) {
          _impl_.num_threads_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional float cpu_percent = 8;
      case 8:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 69)) {
          _Internal::set_has_cpu_percent(&has_bits);
          _impl_.cpu_percent_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // optional int32 num_child_processes = 9;
      case 9:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 72)) {
          _Internal::set_has_num_child_processes(&has_bits);
          _impl_.num_child_processes_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional float memory_percent = 10;
      case 10:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 85)) {
          _Internal::set_has_memory_percent(&has_bits);
          _impl_.memory_percent_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr);
          ptr += sizeof(float);
        } else
          goto handle_unusual;
        continue;
      // optional uint64 read_bytes_kb = 11;
      case 11:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 88)) {
          _Internal::set_has_read_bytes_kb(&has_bits);
          _impl_.read_bytes_kb_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional uint64 write_bytes_kb = 12;
      case 12:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 96)) {
          _Internal::set_has_write_bytes_kb(&has_bits);
          _impl_.write_bytes_kb_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // optional int32 num_fds = 13;
      case 13:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 104)) {
          _Internal::set_has_num_fds(&has_bits);
          _impl_.num_fds_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 nice = 14;
      case 14:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 112)) {
          _impl_.nice_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // string boottime = 15;
      case 15:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 122)) {
          auto str = _internal_mutable_boottime();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.ProcessMetrics.boottime"));
        } else
          goto handle_unusual;
        continue;
      // string timestartprocess = 16;
      case 16:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 130)) {
          auto str = _internal_mutable_timestartprocess();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.ProcessMetrics.timestartprocess"));
        } else
          goto handle_unusual;
        continue;
      // string hostip = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 138)) {
          auto str = _internal_mutable_hostip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.ProcessMetrics.hostip"));
        } else
          goto handle_unusual;
        continue;
      // int32 ionice_value = 20;
      case 20:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 160)) {
          _impl_.ionice_value_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 gid_effective = 21;
      case 21:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 168)) {
          _impl_.gid_effective_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 mem_rss_kb = 23;
      case 23:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 184)) {
          _impl_.mem_rss_kb_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 mem_shared_kb = 25;
      case 25:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 200)) {
          _impl_.mem_shared_kb_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 mem_vms_kb = 26;
      case 26:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 208)) {
          _impl_.mem_vms_kb_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      // int32 mem_text_kb = 27;
      case 27:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 216)) {
          _impl_.mem_text_kb_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  _impl_._has_bits_.Or(has_bits);
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProcessMetrics::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProcessMetricas.ProcessMetrics)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 pid = 1;
  if (this->_internal_pid() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(1, this->_internal_pid(), target);
  }

  // string name = 2;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.ProcessMetrics.name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_name(), target);
  }

  // string user = 3;
  if (!this->_internal_user().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_user().data(), static_cast<int>(this->_internal_user().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.ProcessMetrics.user");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_user(), target);
  }

  // string timestamp = 4;
  if (!this->_internal_timestamp().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_timestamp().data(), static_cast<int>(this->_internal_timestamp().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.ProcessMetrics.timestamp");
    target = stream->WriteStringMaybeAliased(
        4, this->_internal_timestamp(), target);
  }

  // int32 num_threads = 7;
  if (this->_internal_num_threads() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(7, this->_internal_num_threads(), target);
  }

  // optional float cpu_percent = 8;
  if (_internal_has_cpu_percent()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(8, this->_internal_cpu_percent(), target);
  }

  // optional int32 num_child_processes = 9;
  if (_internal_has_num_child_processes()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(9, this->_internal_num_child_processes(), target);
  }

  // optional float memory_percent = 10;
  if (_internal_has_memory_percent()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteFloatToArray(10, this->_internal_memory_percent(), target);
  }

  // optional uint64 read_bytes_kb = 11;
  if (_internal_has_read_bytes_kb()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(11, this->_internal_read_bytes_kb(), target);
  }

  // optional uint64 write_bytes_kb = 12;
  if (_internal_has_write_bytes_kb()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt64ToArray(12, this->_internal_write_bytes_kb(), target);
  }

  // optional int32 num_fds = 13;
  if (_internal_has_num_fds()) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(13, this->_internal_num_fds(), target);
  }

  // int32 nice = 14;
  if (this->_internal_nice() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(14, this->_internal_nice(), target);
  }

  // string boottime = 15;
  if (!this->_internal_boottime().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_boottime().data(), static_cast<int>(this->_internal_boottime().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.ProcessMetrics.boottime");
    target = stream->WriteStringMaybeAliased(
        15, this->_internal_boottime(), target);
  }

  // string timestartprocess = 16;
  if (!this->_internal_timestartprocess().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_timestartprocess().data(), static_cast<int>(this->_internal_timestartprocess().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.ProcessMetrics.timestartprocess");
    target = stream->WriteStringMaybeAliased(
        16, this->_internal_timestartprocess(), target);
  }

  // string hostip = 17;
  if (!this->_internal_hostip().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hostip().data(), static_cast<int>(this->_internal_hostip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.ProcessMetrics.hostip");
    target = stream->WriteStringMaybeAliased(
        17, this->_internal_hostip(), target);
  }

  // int32 ionice_value = 20;
  if (this->_internal_ionice_value() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(20, this->_internal_ionice_value(), target);
  }

  // int32 gid_effective = 21;
  if (this->_internal_gid_effective() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(21, this->_internal_gid_effective(), target);
  }

  // int32 mem_rss_kb = 23;
  if (this->_internal_mem_rss_kb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(23, this->_internal_mem_rss_kb(), target);
  }

  // int32 mem_shared_kb = 25;
  if (this->_internal_mem_shared_kb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(25, this->_internal_mem_shared_kb(), target);
  }

  // int32 mem_vms_kb = 26;
  if (this->_internal_mem_vms_kb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(26, this->_internal_mem_vms_kb(), target);
  }

  // int32 mem_text_kb = 27;
  if (this->_internal_mem_text_kb() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteInt32ToArray(27, this->_internal_mem_text_kb(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProcessMetricas.ProcessMetrics)
  return target;
}

size_t ProcessMetrics::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProcessMetricas.ProcessMetrics)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 2;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string user = 3;
  if (!this->_internal_user().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_user());
  }

  // string timestamp = 4;
  if (!this->_internal_timestamp().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_timestamp());
  }

  // string boottime = 15;
  if (!this->_internal_boottime().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_boottime());
  }

  // string timestartprocess = 16;
  if (!this->_internal_timestartprocess().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_timestartprocess());
  }

  // string hostip = 17;
  if (!this->_internal_hostip().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hostip());
  }

  // int32 pid = 1;
  if (this->_internal_pid() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_pid());
  }

  // int32 num_threads = 7;
  if (this->_internal_num_threads() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_num_threads());
  }

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    // optional float cpu_percent = 8;
    if (cached_has_bits & 0x00000001u) {
      total_size += 1 + 4;
    }

    // optional int32 num_child_processes = 9;
    if (cached_has_bits & 0x00000002u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_num_child_processes());
    }

    // optional uint64 read_bytes_kb = 11;
    if (cached_has_bits & 0x00000004u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_read_bytes_kb());
    }

    // optional float memory_percent = 10;
    if (cached_has_bits & 0x00000008u) {
      total_size += 1 + 4;
    }

    // optional int32 num_fds = 13;
    if (cached_has_bits & 0x00000010u) {
      total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_num_fds());
    }

    // optional uint64 write_bytes_kb = 12;
    if (cached_has_bits & 0x00000020u) {
      total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(this->_internal_write_bytes_kb());
    }

  }
  // int32 nice = 14;
  if (this->_internal_nice() != 0) {
    total_size += ::_pbi::WireFormatLite::Int32SizePlusOne(this->_internal_nice());
  }

  // int32 ionice_value = 20;
  if (this->_internal_ionice_value() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_ionice_value());
  }

  // int32 gid_effective = 21;
  if (this->_internal_gid_effective() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_gid_effective());
  }

  // int32 mem_rss_kb = 23;
  if (this->_internal_mem_rss_kb() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_mem_rss_kb());
  }

  // int32 mem_shared_kb = 25;
  if (this->_internal_mem_shared_kb() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_mem_shared_kb());
  }

  // int32 mem_vms_kb = 26;
  if (this->_internal_mem_vms_kb() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_mem_vms_kb());
  }

  // int32 mem_text_kb = 27;
  if (this->_internal_mem_text_kb() != 0) {
    total_size += 2 +
      ::_pbi::WireFormatLite::Int32Size(
        this->_internal_mem_text_kb());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProcessMetrics::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProcessMetrics::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProcessMetrics::GetClassData() const { return &_class_data_; }


void ProcessMetrics::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProcessMetrics*>(&to_msg);
  auto& from = static_cast<const ProcessMetrics&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ProcessMetricas.ProcessMetrics)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_user().empty()) {
    _this->_internal_set_user(from._internal_user());
  }
  if (!from._internal_timestamp().empty()) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  if (!from._internal_boottime().empty()) {
    _this->_internal_set_boottime(from._internal_boottime());
  }
  if (!from._internal_timestartprocess().empty()) {
    _this->_internal_set_timestartprocess(from._internal_timestartprocess());
  }
  if (!from._internal_hostip().empty()) {
    _this->_internal_set_hostip(from._internal_hostip());
  }
  if (from._internal_pid() != 0) {
    _this->_internal_set_pid(from._internal_pid());
  }
  if (from._internal_num_threads() != 0) {
    _this->_internal_set_num_threads(from._internal_num_threads());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x0000003fu) {
    if (cached_has_bits & 0x00000001u) {
      _this->_impl_.cpu_percent_ = from._impl_.cpu_percent_;
    }
    if (cached_has_bits & 0x00000002u) {
      _this->_impl_.num_child_processes_ = from._impl_.num_child_processes_;
    }
    if (cached_has_bits & 0x00000004u) {
      _this->_impl_.read_bytes_kb_ = from._impl_.read_bytes_kb_;
    }
    if (cached_has_bits & 0x00000008u) {
      _this->_impl_.memory_percent_ = from._impl_.memory_percent_;
    }
    if (cached_has_bits & 0x00000010u) {
      _this->_impl_.num_fds_ = from._impl_.num_fds_;
    }
    if (cached_has_bits & 0x00000020u) {
      _this->_impl_.write_bytes_kb_ = from._impl_.write_bytes_kb_;
    }
    _this->_impl_._has_bits_[0] |= cached_has_bits;
  }
  if (from._internal_nice() != 0) {
    _this->_internal_set_nice(from._internal_nice());
  }
  if (from._internal_ionice_value() != 0) {
    _this->_internal_set_ionice_value(from._internal_ionice_value());
  }
  if (from._internal_gid_effective() != 0) {
    _this->_internal_set_gid_effective(from._internal_gid_effective());
  }
  if (from._internal_mem_rss_kb() != 0) {
    _this->_internal_set_mem_rss_kb(from._internal_mem_rss_kb());
  }
  if (from._internal_mem_shared_kb() != 0) {
    _this->_internal_set_mem_shared_kb(from._internal_mem_shared_kb());
  }
  if (from._internal_mem_vms_kb() != 0) {
    _this->_internal_set_mem_vms_kb(from._internal_mem_vms_kb());
  }
  if (from._internal_mem_text_kb() != 0) {
    _this->_internal_set_mem_text_kb(from._internal_mem_text_kb());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProcessMetrics::CopyFrom(const ProcessMetrics& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProcessMetricas.ProcessMetrics)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProcessMetrics::IsInitialized() const {
  return true;
}

void ProcessMetrics::InternalSwap(ProcessMetrics* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.user_, lhs_arena,
      &other->_impl_.user_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.timestamp_, lhs_arena,
      &other->_impl_.timestamp_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.boottime_, lhs_arena,
      &other->_impl_.boottime_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.timestartprocess_, lhs_arena,
      &other->_impl_.timestartprocess_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.hostip_, lhs_arena,
      &other->_impl_.hostip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::memswap<
      PROTOBUF_FIELD_OFFSET(ProcessMetrics, _impl_.mem_text_kb_)
      + sizeof(ProcessMetrics::_impl_.mem_text_kb_)
      - PROTOBUF_FIELD_OFFSET(ProcessMetrics, _impl_.pid_)>(
          reinterpret_cast<char*>(&_impl_.pid_),
          reinterpret_cast<char*>(&other->_impl_.pid_));
}

::PROTOBUF_NAMESPACE_ID::Metadata ProcessMetrics::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProcessMetricas_2eproto_getter, &descriptor_table_ProcessMetricas_2eproto_once,
      file_level_metadata_ProcessMetricas_2eproto[0]);
}

// ===================================================================

class ProcessMetricsList::_Internal {
 public:
};

ProcessMetricsList::ProcessMetricsList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ProcessMetricas.ProcessMetricsList)
}
ProcessMetricsList::ProcessMetricsList(const ProcessMetricsList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  ProcessMetricsList* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.processes_){from._impl_.processes_}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ProcessMetricas.ProcessMetricsList)
}

inline void ProcessMetricsList::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.processes_){arena}
    , /*decltype(_impl_._cached_size_)*/{}
  };
}

ProcessMetricsList::~ProcessMetricsList() {
  // @@protoc_insertion_point(destructor:ProcessMetricas.ProcessMetricsList)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void ProcessMetricsList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.processes_.~RepeatedPtrField();
}

void ProcessMetricsList::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void ProcessMetricsList::Clear() {
// @@protoc_insertion_point(message_clear_start:ProcessMetricas.ProcessMetricsList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.processes_.Clear();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* ProcessMetricsList::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .ProcessMetricas.ProcessMetrics processes = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_processes(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* ProcessMetricsList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProcessMetricas.ProcessMetricsList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ProcessMetricas.ProcessMetrics processes = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_processes_size()); i < n; i++) {
    const auto& repfield = this->_internal_processes(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProcessMetricas.ProcessMetricsList)
  return target;
}

size_t ProcessMetricsList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProcessMetricas.ProcessMetricsList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ProcessMetricas.ProcessMetrics processes = 1;
  total_size += 1UL * this->_internal_processes_size();
  for (const auto& msg : this->_impl_.processes_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData ProcessMetricsList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    ProcessMetricsList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*ProcessMetricsList::GetClassData() const { return &_class_data_; }


void ProcessMetricsList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<ProcessMetricsList*>(&to_msg);
  auto& from = static_cast<const ProcessMetricsList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ProcessMetricas.ProcessMetricsList)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.processes_.MergeFrom(from._impl_.processes_);
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void ProcessMetricsList::CopyFrom(const ProcessMetricsList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProcessMetricas.ProcessMetricsList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ProcessMetricsList::IsInitialized() const {
  return true;
}

void ProcessMetricsList::InternalSwap(ProcessMetricsList* other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.processes_.InternalSwap(&other->_impl_.processes_);
}

::PROTOBUF_NAMESPACE_ID::Metadata ProcessMetricsList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProcessMetricas_2eproto_getter, &descriptor_table_ProcessMetricas_2eproto_once,
      file_level_metadata_ProcessMetricas_2eproto[1]);
}

// ===================================================================

class KernelDistro::_Internal {
 public:
};

KernelDistro::KernelDistro(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ProcessMetricas.KernelDistro)
}
KernelDistro::KernelDistro(const KernelDistro& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  KernelDistro* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.kernel_version_){}
    , decltype(_impl_.distro_name_){}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.hostip_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.kernel_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.kernel_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_kernel_version().empty()) {
    _this->_impl_.kernel_version_.Set(from._internal_kernel_version(), 
      _this->GetArenaForAllocation());
  }
  _impl_.distro_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.distro_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_distro_name().empty()) {
    _this->_impl_.distro_name_.Set(from._internal_distro_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.timestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_timestamp().empty()) {
    _this->_impl_.timestamp_.Set(from._internal_timestamp(), 
      _this->GetArenaForAllocation());
  }
  _impl_.hostip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hostip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_hostip().empty()) {
    _this->_impl_.hostip_.Set(from._internal_hostip(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ProcessMetricas.KernelDistro)
}

inline void KernelDistro::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.kernel_version_){}
    , decltype(_impl_.distro_name_){}
    , decltype(_impl_.timestamp_){}
    , decltype(_impl_.hostip_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.kernel_version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.kernel_version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.distro_name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.distro_name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.timestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.hostip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hostip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

KernelDistro::~KernelDistro() {
  // @@protoc_insertion_point(destructor:ProcessMetricas.KernelDistro)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void KernelDistro::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.kernel_version_.Destroy();
  _impl_.distro_name_.Destroy();
  _impl_.timestamp_.Destroy();
  _impl_.hostip_.Destroy();
}

void KernelDistro::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void KernelDistro::Clear() {
// @@protoc_insertion_point(message_clear_start:ProcessMetricas.KernelDistro)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.kernel_version_.ClearToEmpty();
  _impl_.distro_name_.ClearToEmpty();
  _impl_.timestamp_.ClearToEmpty();
  _impl_.hostip_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* KernelDistro::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string kernel_version = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_kernel_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.KernelDistro.kernel_version"));
        } else
          goto handle_unusual;
        continue;
      // string distro_name = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_distro_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.KernelDistro.distro_name"));
        } else
          goto handle_unusual;
        continue;
      // string timestamp = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_timestamp();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.KernelDistro.timestamp"));
        } else
          goto handle_unusual;
        continue;
      // string hostip = 17;
      case 17:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 138)) {
          auto str = _internal_mutable_hostip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.KernelDistro.hostip"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* KernelDistro::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProcessMetricas.KernelDistro)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string kernel_version = 1;
  if (!this->_internal_kernel_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_kernel_version().data(), static_cast<int>(this->_internal_kernel_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.KernelDistro.kernel_version");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_kernel_version(), target);
  }

  // string distro_name = 2;
  if (!this->_internal_distro_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_distro_name().data(), static_cast<int>(this->_internal_distro_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.KernelDistro.distro_name");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_distro_name(), target);
  }

  // string timestamp = 3;
  if (!this->_internal_timestamp().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_timestamp().data(), static_cast<int>(this->_internal_timestamp().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.KernelDistro.timestamp");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_timestamp(), target);
  }

  // string hostip = 17;
  if (!this->_internal_hostip().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hostip().data(), static_cast<int>(this->_internal_hostip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.KernelDistro.hostip");
    target = stream->WriteStringMaybeAliased(
        17, this->_internal_hostip(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProcessMetricas.KernelDistro)
  return target;
}

size_t KernelDistro::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProcessMetricas.KernelDistro)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string kernel_version = 1;
  if (!this->_internal_kernel_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_kernel_version());
  }

  // string distro_name = 2;
  if (!this->_internal_distro_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_distro_name());
  }

  // string timestamp = 3;
  if (!this->_internal_timestamp().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_timestamp());
  }

  // string hostip = 17;
  if (!this->_internal_hostip().empty()) {
    total_size += 2 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hostip());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData KernelDistro::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    KernelDistro::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*KernelDistro::GetClassData() const { return &_class_data_; }


void KernelDistro::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<KernelDistro*>(&to_msg);
  auto& from = static_cast<const KernelDistro&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ProcessMetricas.KernelDistro)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_kernel_version().empty()) {
    _this->_internal_set_kernel_version(from._internal_kernel_version());
  }
  if (!from._internal_distro_name().empty()) {
    _this->_internal_set_distro_name(from._internal_distro_name());
  }
  if (!from._internal_timestamp().empty()) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  if (!from._internal_hostip().empty()) {
    _this->_internal_set_hostip(from._internal_hostip());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void KernelDistro::CopyFrom(const KernelDistro& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProcessMetricas.KernelDistro)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool KernelDistro::IsInitialized() const {
  return true;
}

void KernelDistro::InternalSwap(KernelDistro* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.kernel_version_, lhs_arena,
      &other->_impl_.kernel_version_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.distro_name_, lhs_arena,
      &other->_impl_.distro_name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.timestamp_, lhs_arena,
      &other->_impl_.timestamp_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.hostip_, lhs_arena,
      &other->_impl_.hostip_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata KernelDistro::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProcessMetricas_2eproto_getter, &descriptor_table_ProcessMetricas_2eproto_once,
      file_level_metadata_ProcessMetricas_2eproto[2]);
}

// ===================================================================

class InstalledProgram::_Internal {
 public:
};

InstalledProgram::InstalledProgram(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ProcessMetricas.InstalledProgram)
}
InstalledProgram::InstalledProgram(const InstalledProgram& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InstalledProgram* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.version_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), 
      _this->GetArenaForAllocation());
  }
  _impl_.version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_version().empty()) {
    _this->_impl_.version_.Set(from._internal_version(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ProcessMetricas.InstalledProgram)
}

inline void InstalledProgram::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.name_){}
    , decltype(_impl_.version_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.name_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.version_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.version_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

InstalledProgram::~InstalledProgram() {
  // @@protoc_insertion_point(destructor:ProcessMetricas.InstalledProgram)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InstalledProgram::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.name_.Destroy();
  _impl_.version_.Destroy();
}

void InstalledProgram::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InstalledProgram::Clear() {
// @@protoc_insertion_point(message_clear_start:ProcessMetricas.InstalledProgram)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  _impl_.version_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InstalledProgram::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // string name = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          auto str = _internal_mutable_name();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.InstalledProgram.name"));
        } else
          goto handle_unusual;
        continue;
      // string version = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_version();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.InstalledProgram.version"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InstalledProgram::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProcessMetricas.InstalledProgram)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_name().data(), static_cast<int>(this->_internal_name().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.InstalledProgram.name");
    target = stream->WriteStringMaybeAliased(
        1, this->_internal_name(), target);
  }

  // string version = 2;
  if (!this->_internal_version().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_version().data(), static_cast<int>(this->_internal_version().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.InstalledProgram.version");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_version(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProcessMetricas.InstalledProgram)
  return target;
}

size_t InstalledProgram::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProcessMetricas.InstalledProgram)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_name());
  }

  // string version = 2;
  if (!this->_internal_version().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_version());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InstalledProgram::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InstalledProgram::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InstalledProgram::GetClassData() const { return &_class_data_; }


void InstalledProgram::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InstalledProgram*>(&to_msg);
  auto& from = static_cast<const InstalledProgram&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ProcessMetricas.InstalledProgram)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (!from._internal_version().empty()) {
    _this->_internal_set_version(from._internal_version());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InstalledProgram::CopyFrom(const InstalledProgram& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProcessMetricas.InstalledProgram)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InstalledProgram::IsInitialized() const {
  return true;
}

void InstalledProgram::InternalSwap(InstalledProgram* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.name_, lhs_arena,
      &other->_impl_.name_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.version_, lhs_arena,
      &other->_impl_.version_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata InstalledProgram::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProcessMetricas_2eproto_getter, &descriptor_table_ProcessMetricas_2eproto_once,
      file_level_metadata_ProcessMetricas_2eproto[3]);
}

// ===================================================================

class InstalledProgramList::_Internal {
 public:
};

InstalledProgramList::InstalledProgramList(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                         bool is_message_owned)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena, is_message_owned) {
  SharedCtor(arena, is_message_owned);
  // @@protoc_insertion_point(arena_constructor:ProcessMetricas.InstalledProgramList)
}
InstalledProgramList::InstalledProgramList(const InstalledProgramList& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  InstalledProgramList* const _this = this; (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_.programs_){from._impl_.programs_}
    , decltype(_impl_.hostip_){}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}};

  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  _impl_.hostip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hostip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_hostip().empty()) {
    _this->_impl_.hostip_.Set(from._internal_hostip(), 
      _this->GetArenaForAllocation());
  }
  _impl_.timestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_timestamp().empty()) {
    _this->_impl_.timestamp_.Set(from._internal_timestamp(), 
      _this->GetArenaForAllocation());
  }
  // @@protoc_insertion_point(copy_constructor:ProcessMetricas.InstalledProgramList)
}

inline void InstalledProgramList::SharedCtor(
    ::_pb::Arena* arena, bool is_message_owned) {
  (void)arena;
  (void)is_message_owned;
  new (&_impl_) Impl_{
      decltype(_impl_.programs_){arena}
    , decltype(_impl_.hostip_){}
    , decltype(_impl_.timestamp_){}
    , /*decltype(_impl_._cached_size_)*/{}
  };
  _impl_.hostip_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.hostip_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  _impl_.timestamp_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
    _impl_.timestamp_.Set("", GetArenaForAllocation());
  #endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}

InstalledProgramList::~InstalledProgramList() {
  // @@protoc_insertion_point(destructor:ProcessMetricas.InstalledProgramList)
  if (auto *arena = _internal_metadata_.DeleteReturnArena<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>()) {
  (void)arena;
    return;
  }
  SharedDtor();
}

inline void InstalledProgramList::SharedDtor() {
  GOOGLE_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.programs_.~RepeatedPtrField();
  _impl_.hostip_.Destroy();
  _impl_.timestamp_.Destroy();
}

void InstalledProgramList::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

void InstalledProgramList::Clear() {
// @@protoc_insertion_point(message_clear_start:ProcessMetricas.InstalledProgramList)
  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.programs_.Clear();
  _impl_.hostip_.ClearToEmpty();
  _impl_.timestamp_.ClearToEmpty();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* InstalledProgramList::_InternalParse(const char* ptr, ::_pbi::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    uint32_t tag;
    ptr = ::_pbi::ReadTag(ptr, &tag);
    switch (tag >> 3) {
      // repeated .ProcessMetricas.InstalledProgram programs = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 10)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_programs(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<10>(ptr));
        } else
          goto handle_unusual;
        continue;
      // string hostip = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 18)) {
          auto str = _internal_mutable_hostip();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.InstalledProgramList.hostip"));
        } else
          goto handle_unusual;
        continue;
      // string timestamp = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<uint8_t>(tag) == 26)) {
          auto str = _internal_mutable_timestamp();
          ptr = ::_pbi::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(ptr);
          CHK_(::_pbi::VerifyUTF8(str, "ProcessMetricas.InstalledProgramList.timestamp"));
        } else
          goto handle_unusual;
        continue;
      default:
        goto handle_unusual;
    }  // switch
  handle_unusual:
    if ((tag == 0) || ((tag & 7) == 4)) {
      CHK_(ptr);
      ctx->SetLastTag(tag);
      goto message_done;
    }
    ptr = UnknownFieldParse(
        tag,
        _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
        ptr, ctx);
    CHK_(ptr != nullptr);
  }  // while
message_done:
  return ptr;
failure:
  ptr = nullptr;
  goto message_done;
#undef CHK_
}

uint8_t* InstalledProgramList::_InternalSerialize(
    uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:ProcessMetricas.InstalledProgramList)
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ProcessMetricas.InstalledProgram programs = 1;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_programs_size()); i < n; i++) {
    const auto& repfield = this->_internal_programs(i);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
        InternalWriteMessage(1, repfield, repfield.GetCachedSize(), target, stream);
  }

  // string hostip = 2;
  if (!this->_internal_hostip().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_hostip().data(), static_cast<int>(this->_internal_hostip().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.InstalledProgramList.hostip");
    target = stream->WriteStringMaybeAliased(
        2, this->_internal_hostip(), target);
  }

  // string timestamp = 3;
  if (!this->_internal_timestamp().empty()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_timestamp().data(), static_cast<int>(this->_internal_timestamp().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "ProcessMetricas.InstalledProgramList.timestamp");
    target = stream->WriteStringMaybeAliased(
        3, this->_internal_timestamp(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ProcessMetricas.InstalledProgramList)
  return target;
}

size_t InstalledProgramList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ProcessMetricas.InstalledProgramList)
  size_t total_size = 0;

  uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ProcessMetricas.InstalledProgram programs = 1;
  total_size += 1UL * this->_internal_programs_size();
  for (const auto& msg : this->_impl_.programs_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // string hostip = 2;
  if (!this->_internal_hostip().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_hostip());
  }

  // string timestamp = 3;
  if (!this->_internal_timestamp().empty()) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
        this->_internal_timestamp());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::PROTOBUF_NAMESPACE_ID::Message::ClassData InstalledProgramList::_class_data_ = {
    ::PROTOBUF_NAMESPACE_ID::Message::CopyWithSourceCheck,
    InstalledProgramList::MergeImpl
};
const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*InstalledProgramList::GetClassData() const { return &_class_data_; }


void InstalledProgramList::MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg) {
  auto* const _this = static_cast<InstalledProgramList*>(&to_msg);
  auto& from = static_cast<const InstalledProgramList&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:ProcessMetricas.InstalledProgramList)
  GOOGLE_DCHECK_NE(&from, _this);
  uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_impl_.programs_.MergeFrom(from._impl_.programs_);
  if (!from._internal_hostip().empty()) {
    _this->_internal_set_hostip(from._internal_hostip());
  }
  if (!from._internal_timestamp().empty()) {
    _this->_internal_set_timestamp(from._internal_timestamp());
  }
  _this->_internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
}

void InstalledProgramList::CopyFrom(const InstalledProgramList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ProcessMetricas.InstalledProgramList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool InstalledProgramList::IsInitialized() const {
  return true;
}

void InstalledProgramList::InternalSwap(InstalledProgramList* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  _impl_.programs_.InternalSwap(&other->_impl_.programs_);
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.hostip_, lhs_arena,
      &other->_impl_.hostip_, rhs_arena
  );
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::InternalSwap(
      &_impl_.timestamp_, lhs_arena,
      &other->_impl_.timestamp_, rhs_arena
  );
}

::PROTOBUF_NAMESPACE_ID::Metadata InstalledProgramList::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_ProcessMetricas_2eproto_getter, &descriptor_table_ProcessMetricas_2eproto_once,
      file_level_metadata_ProcessMetricas_2eproto[4]);
}

// @@protoc_insertion_point(namespace_scope)
}  // namespace ProcessMetricas
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::ProcessMetricas::ProcessMetrics*
Arena::CreateMaybeMessage< ::ProcessMetricas::ProcessMetrics >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProcessMetricas::ProcessMetrics >(arena);
}
template<> PROTOBUF_NOINLINE ::ProcessMetricas::ProcessMetricsList*
Arena::CreateMaybeMessage< ::ProcessMetricas::ProcessMetricsList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProcessMetricas::ProcessMetricsList >(arena);
}
template<> PROTOBUF_NOINLINE ::ProcessMetricas::KernelDistro*
Arena::CreateMaybeMessage< ::ProcessMetricas::KernelDistro >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProcessMetricas::KernelDistro >(arena);
}
template<> PROTOBUF_NOINLINE ::ProcessMetricas::InstalledProgram*
Arena::CreateMaybeMessage< ::ProcessMetricas::InstalledProgram >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProcessMetricas::InstalledProgram >(arena);
}
template<> PROTOBUF_NOINLINE ::ProcessMetricas::InstalledProgramList*
Arena::CreateMaybeMessage< ::ProcessMetricas::InstalledProgramList >(Arena* arena) {
  return Arena::CreateMessageInternal< ::ProcessMetricas::InstalledProgramList >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
