
# Configuration file for the monitoring agent
username=galmeidalopes

# Hostname or IP address of the server to send data to
server_host=192.168.0.8

# Port number for the server to listen on
server_port=9995

# Buffer size for data processing
BufferSize=1

# Number of threads
NumberOfThreads=8

# Sleep time between reads in seconds
TimeSpleepBetweenReads=15

# Configuration file for the monitoring agent
laboratory=E100


