# Configuration file for the monitoring agent

# Hostname or IP address of the server to send data to
server_host=0.0.0.0
# Port number for the server to listen on
server_port=9995

# Buffer size for data processing
BufferSize=4096

# Number of threads
NumberOfThreads=8

# Periodic script execution interval in hours
TruePeriodicScriptHours=1

# Sleep time between reads in seconds
TimeSpleepBetweenReads=15


